'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs').promises;
const path=require('node:path');
const os=require('node:os');
const yauzl=require('yauzl');
const yazl=require('yazl');
const {inspectPptVideos,removePptVideos}=require('../src/ppt-video-remover');
const {ffmpegPath}=require('../src/video-processor');
const {spawn}=require('node:child_process');

const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
async function fixture(file,video=Buffer.alloc(2048,7)){const zip=new yazl.ZipFile(),chunks=[];zip.outputStream.on('data',chunk=>chunks.push(chunk));const finished=new Promise((resolve,reject)=>{zip.outputStream.on('end',resolve);zip.outputStream.on('error',reject);});zip.addBuffer(Buffer.from('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="png" ContentType="image/png"/><Default Extension="mp4" ContentType="video/mp4"/></Types>'),'[Content_Types].xml');zip.addBuffer(Buffer.from('<p:sld xmlns:p="p" xmlns:a="a" xmlns:r="r" xmlns:p14="p14"><p:cSld><p:spTree><p:pic><p:nvPicPr><p:nvPr><a:videoFile r:link="rIdVideo"/><p14:media r:embed="rIdMedia"/></p:nvPr></p:nvPicPr><p:blipFill><a:blip r:embed="rIdPoster"/></p:blipFill></p:pic></p:spTree></p:cSld></p:sld>'),'ppt/slides/slide1.xml');zip.addBuffer(Buffer.from('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdVideo" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/video" Target="../media/media1.mp4"/><Relationship Id="rIdMedia" Type="http://schemas.microsoft.com/office/2007/relationships/media" Target="../media/media1.mp4"/><Relationship Id="rIdPoster" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/image1.png"/></Relationships>'),'ppt/slides/_rels/slide1.xml.rels');zip.addBuffer(video,'ppt/media/media1.mp4');zip.addBuffer(png,'ppt/media/image1.png');zip.end();await finished;await fs.writeFile(file,Buffer.concat(chunks));}
function run(binary,args){return new Promise((resolve,reject)=>{const child=spawn(binary,args,{stdio:'ignore',windowsHide:true});child.on('error',reject);child.on('close',code=>code===0?resolve():reject(new Error(`process exited ${code}`)));});}
async function entries(file){const input=await fs.readFile(file);return new Promise((resolve,reject)=>yauzl.fromBuffer(input,{lazyEntries:true},(error,zip)=>{if(error)return reject(error);const result=new Map();zip.on('entry',entry=>zip.openReadStream(entry,(failure,stream)=>{if(failure)return reject(failure);const chunks=[];stream.on('data',chunk=>chunks.push(chunk));stream.on('end',()=>{result.set(entry.fileName,Buffer.concat(chunks));zip.readEntry();});}));zip.on('end',()=>resolve(result));zip.on('error',reject);zip.readEntry();}));}

test('PPT video removal keeps the poster frame and removes embedded video data',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'presalesx-ppt-video-')),source=path.join(directory,'source.pptx'),destination=path.join(directory,'clean.pptx');try{await fixture(source);const inspected=await inspectPptVideos(source);assert.equal(inspected.videos.length,1);assert.deepEqual(inspected.videos[0].slides,[1]);assert.equal(inspected.videos[0].hasPoster,true);const result=await removePptVideos({sourcePath:source,destination,selections:[{id:inspected.videos[0].id,mode:'poster'}]});assert.equal(result.removed,1);assert.ok(result.afterBytes<result.beforeBytes);const output=await entries(destination),slide=output.get('ppt/slides/slide1.xml').toString(),rels=output.get('ppt/slides/_rels/slide1.xml.rels').toString();assert.equal(output.has('ppt/media/media1.mp4'),false);assert.equal(output.has('ppt/media/image1.png'),true);assert.doesNotMatch(slide,/videoFile|p14:media/);assert.doesNotMatch(rels,/media1\.mp4/);assert.match(rels,/image1\.png/);}finally{await fs.rm(directory,{recursive:true,force:true});}});
test('PPT video removal can replace the poster relationship with the extracted first frame',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'presalesx-ppt-first-frame-')),video=path.join(directory,'video.mp4'),source=path.join(directory,'source.pptx'),destination=path.join(directory,'clean.pptx');try{await run(ffmpegPath(),['-y','-f','lavfi','-i','color=c=red:s=160x90:d=1','-c:v','libx264','-pix_fmt','yuv420p',video]);await fixture(source,await fs.readFile(video));const inspected=await inspectPptVideos(source);await removePptVideos({sourcePath:source,destination,selections:[{id:inspected.videos[0].id,mode:'firstFrame'}]});const output=await entries(destination),rels=output.get('ppt/slides/_rels/slide1.xml.rels').toString(),frame=[...output.keys()].find(name=>/presalesx-video-frame-\d+\.png$/.test(name));assert.ok(frame);assert.ok(output.get(frame).length>png.length);assert.match(rels,/presalesx-video-frame-1\.png/);assert.doesNotMatch(rels,/media1\.mp4/);}finally{await fs.rm(directory,{recursive:true,force:true});}});
