'use strict';

let inputFiles=[],project=null,mode='compare',activeSection='overview',selectedFileKey='',metadataLinkState=new Map(),supplierFilters={exact:false,attribute:false},sanitizationFiles=[],activeSanitizationIndex=0,imageSourceFiles=[],activeImageFileIndex=0,watermarkImage=null,activePreviewImageId='',activeCompressionTarget=null,imageFileTypeFilters=new Set(),imageFileSizeSort='default',colorPreviewState=null,colorPreviewVersion=0,galleryRenderVersion=0,galleryObserver=null,galleryClickTimer=0,previewLoadVersion=0;
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const metadataTimeFields=new Set(['created','modified','lastPrinted']);
function currentWatermarkTime(){const date=new Date(),part=value=>String(value).padStart(2,'0');return `${date.getFullYear()}-${part(date.getMonth()+1)}-${part(date.getDate())} ${part(date.getHours())}:${part(date.getMinutes())}:${part(date.getSeconds())}`;}
function refreshWatermarkTime(){const input=$('#watermarkText');if(input)input.value=currentWatermarkTime();}
function toLocalDateTime(value){if(!value)return '';const date=new Date(value);if(Number.isNaN(date.getTime()))return '';const part=number=>String(number).padStart(2,'0');return `${date.getFullYear()}-${part(date.getMonth()+1)}-${part(date.getDate())}T${part(date.getHours())}:${part(date.getMinutes())}:${part(date.getSeconds())}`;}
function fromLocalDateTime(value){if(!value)return '';const date=new Date(value);return Number.isNaN(date.getTime())?'':date.toISOString();}
const fmt=value=>{const n=Number(value)||0;if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(1)} GB`;};
const typeName=kind=>({pdf:'PDF',word:'Word',excel:'Excel',powerpoint:'PowerPoint',image:'图片',text:'文本',zip:'ZIP',mixed:'多类型'}[kind]||'其他');
const extensionLabel=file=>((String(file?.name||file?.sourcePath||file).match(/\.([^.\\/]+)$/)||[])[1]||'file').toLowerCase();
function syncFilePaneWidth(){const scale=Math.max(1,Number(window.devicePixelRatio)||1),cssPixels=Math.round(600/scale);document.documentElement.style.setProperty('--file-pane-width',`${cssPixels}px`);document.documentElement.dataset.displayScale=String(scale);}
syncFilePaneWidth();window.addEventListener('resize',syncFilePaneWidth);
const views=['start','working','compareWorkspace','editorWorkspace','watermarkWorkspace','imageWorkspace'];
function showView(id){for(const view of views)$('#'+view).hidden=view!==id;$('#propertyDrawer').hidden=true;$('#workspaceTitle').textContent=id==='start'?'开始':id==='working'?'正在处理':id==='compareWorkspace'?'供应商批量审查':id==='watermarkWorkspace'?'文件脱敏':id==='imageWorkspace'?'文档媒体助理':'文件属性编辑器';}
function setStatus(message){$('#statusText').textContent=message;}
async function showDocumentFileMenu(sourcePath,onRemove){if(!sourcePath)return;const action=await window.api.showFileContextMenu({filePath:sourcePath});if(action==='remove'&&onRemove)onRemove();}
document.addEventListener('pointerdown',()=>window.api.companionActivity(),{capture:true});
document.addEventListener('keydown',()=>window.api.companionActivity(),{capture:true});
const showCompanionButton=$('#showCompanion');
showCompanionButton.onclick=()=>{showCompanionButton.hidden=true;window.api.showCompanion();};
window.api.onCompanionVisibility(visible=>{showCompanionButton.hidden=visible;});
function fileKey(file){return `${file.submissionId||''}|${file.supplier||''}|${file.zipPath}`;}
function allFiles(){return (project?.submissions||[]).flatMap(submission=>submission.files.map(file=>({...file,supplier:file.supplier||submission.supplier,submissionId:submission.id,containerPath:submission.zipPath,zipName:submission.zipName,key:`${submission.id}|${submission.supplier}|${file.zipPath}`})));}
function findFile(key){return allFiles().find(file=>file.key===key);}
function updateProjectFile(file,verified){const submission=project?.submissions?.find(item=>item.id===file.submissionId);const target=submission?.files.find(item=>item.zipPath===file.zipPath);if(target){target.attributes=verified.attributes;target.propertyGroups=verified.propertyGroups;target.sha256=verified.sha256;target.size=verified.size;}Object.assign(file,{attributes:verified.attributes,propertyGroups:verified.propertyGroups,sha256:verified.sha256,size:verified.size});}

function setMode(next,{clear=true}={}){mode=next;if(clear)inputFiles=[];$$('.workspace-card').forEach(card=>card.classList.toggle('active',card.dataset.mode===mode));$$('.activity[data-home]').forEach(button=>button.classList.toggle('active',button.dataset.home===mode));const copy={compare:['添加供应商 ZIP','每个 ZIP 文件名将作为一家供应商名称','开始供应商审查'],files:['添加需要编辑的文件','支持 Office、PDF、图片和文本文件','打开文件属性编辑器'],watermark:['添加需要脱敏的文件','支持 Word 和 Excel','打开文件脱敏工作台'],images:['添加需要提取媒体的文件','支持 Word、Excel 和 PowerPoint','打开文档媒体助理']}[mode];$('#dropTitle').textContent=copy[0];$('#dropHint').textContent=copy[1];$('#run').textContent=copy[2];renderChosen();}
function inputTypeLabel(file){return mode==='compare'?'zip':extensionLabel(file);}
function renderChosen(){$('#chosen').innerHTML=inputFiles.map((file,index)=>`<div class="chosen-file"><span class="zip-icon">${inputTypeLabel(file)}</span><div><strong>${esc(file.split(/[\\/]/).pop().replace(mode==='compare'?/\.zip$/i:/$^/,''))}</strong><small>${esc(file)}</small></div><span class="ready">已就绪</span><button class="remove" data-index="${index}">移除</button></div>`).join('');$('#run').disabled=mode==='compare'?inputFiles.length<2:inputFiles.length<1;$$('.chosen-file .remove').forEach(button=>button.onclick=event=>{event.stopPropagation();inputFiles.splice(Number(button.dataset.index),1);renderChosen();});}
async function chooseFiles(){const selected=mode==='compare'?await window.api.pick():mode==='watermark'?await window.api.pickWatermarkFiles():mode==='images'?await window.api.pickImageSourceFiles():await window.api.pickFiles();inputFiles=[...new Set([...inputFiles,...selected])];renderChosen();}
$$('.workspace-card').forEach(card=>card.onclick=()=>setMode(card.dataset.mode));$$('.activity[data-home]').forEach(button=>button.onclick=()=>{showView('start');setMode(button.dataset.home);});
$('#drop').onclick=chooseFiles;$('#drop').ondragover=event=>{event.preventDefault();$('#drop').classList.add('over');};$('#drop').ondragleave=()=>$('#drop').classList.remove('over');$('#drop').ondrop=event=>{event.preventDefault();$('#drop').classList.remove('over');const incoming=[...event.dataTransfer.files].filter(file=>mode==='files'||(mode==='compare'?/\.zip$/i:mode==='images'?/\.(docx|docm|xlsx|xlsm|pptx|pptm)$/i:/\.(docx|docm|xlsx|xlsm)$/i).test(file.name)).map(file=>file.path);inputFiles=[...new Set([...inputFiles,...incoming])];renderChosen();};
window.api.progress(progress=>{const prefix=progress.suppliers?`供应商 ${progress.supplier}/${progress.suppliers} · `:'';$('#step').textContent=`${prefix}${progress.name}`;$('#bar').value=progress.total?progress.done/progress.total*100:0;setStatus(`正在处理 ${progress.name}`);});
window.api.onMediaTaskProgress(task=>{$('#mediaTaskProgress').value=task.progress||0;$('#mediaTaskLabel').textContent=task.label||'处理任务';$('#mediaTaskPercent').textContent=`${Math.round(task.progress||0)}%`;});
window.api.onMediaTaskLog(line=>{const terminal=$('#mediaTaskTerminal');terminal.textContent+=`${line}\n`;terminal.scrollTop=terminal.scrollHeight;});
function beginMediaTask(label,command=''){const terminal=$('#mediaTaskTerminal');terminal.textContent=command?`${command}\n`:'';$('#mediaTaskLabel').textContent=label;$('#mediaTaskPercent').textContent='0%';$('#mediaTaskProgress').value=0;}
function updateMediaTask(progress,line=''){if(line){const terminal=$('#mediaTaskTerminal');terminal.textContent+=`${line}\n`;terminal.scrollTop=terminal.scrollHeight;}$('#mediaTaskProgress').value=progress;$('#mediaTaskPercent').textContent=`${Math.round(progress)}%`;}
$('#run').onclick=async()=>{showView('working');$('#workingTitle').textContent=mode==='watermark'?'正在检查可脱敏内容':mode==='images'?'正在提取内置媒体':'正在本地审查';setStatus('处理中');try{if(mode==='watermark'){sanitizationFiles=await window.api.inspectSanitization(inputFiles);activeSanitizationIndex=0;renderSanitizationWorkspace();showView('watermarkWorkspace');setStatus(`完成 · 已检查 ${sanitizationFiles.length} 个文件`);return;}if(mode==='images'){imageSourceFiles=await window.api.inspectOfficeImages(inputFiles);activeImageFileIndex=0;renderImageWorkspace();showView('imageWorkspace');setStatus(`完成 · 已提取 ${imageSourceFiles.reduce((sum,file)=>sum+file.images.length,0)} 项媒体`);return;}project=await window.api.analyze(inputFiles,{mode});project.operationLog=project.operationLog||[];metadataLinkState.clear();selectedFileKey='';if(mode==='compare'){activeSection='overview';renderCompare();showView('compareWorkspace');}else{renderEditor();showView('editorWorkspace');}setStatus(`完成 · ${allFiles().length} 个文件`);}catch(error){alert('处理失败：'+error.message);showView('start');setStatus('处理失败');}};

function imageDataUrl(image){return image.processedUrl||image.processedData||`data:${image.mime};base64,${image.data}`;}
function mediaMarkup(image,{original=false,controls=false,lazy=false}={}){const source=original?`data:${image.mime};base64,${image.data}`:imageDataUrl(image);if(!image.previewable)return'<div class="image-unavailable">该格式可原样导出<br>当前环境暂不支持预览</div>';return image.mediaType==='video'?`<video src="${source}" ${controls?'controls':''} preload="metadata"></video>`:`<img ${lazy?'loading="lazy" decoding="async" ':''}src="${source}" alt="${esc(image.name)}">`;}
function selectedImageTargets(){const files=imageSourceFiles.filter(file=>file.batchSelected);if(files.length)return files.flatMap(file=>file.images.map(image=>({file,image})));return imageSourceFiles.flatMap(file=>file.images.filter(image=>image.selected).map(image=>({file,image})));}
function findImageTarget(id){for(const file of imageSourceFiles){const image=file.images.find(item=>item.id===id);if(image)return{file,image};}return null;}
function imageCopyPayload(targets){return targets.filter(({image})=>image.mediaType!=='video'&&image.previewable).map(({image})=>({name:image.processedName||image.name,mime:image.processedMime||image.mime,data:image.processedData?image.processedData.split(',')[1]:image.data}));}
function processedSourceTargets(targets=selectedImageTargets()){return targets.filter(({image})=>image.processedData&&image.processedMime===image.mime||image.processedPath&&['mp4','m4v'].includes(image.ext));}
function updateImageActionState(){const selectedFiles=imageSourceFiles.filter(file=>file.batchSelected),targets=selectedImageTargets(),hasImages=targets.some(({image})=>image.processable),videos=targets.filter(({image})=>image.mediaType==='video'),copyable=targets.some(({image})=>image.mediaType!=='video'&&image.previewable)||(targets.length===1&&targets[0].image.processedPath),sourceReady=processedSourceTargets(targets).length>0,single=targets.length===1;if(colorPreviewState&&!targets.some(({image})=>image.id===colorPreviewState.image.id))restoreColorPreview();$('#imageSelectedCount').textContent=targets.length?(selectedFiles.length?`${selectedFiles.length} 个文件 · ${targets.length} 项媒体`:`已选择 ${targets.length} 项`):'请选择媒体';$('#imageBatchActions').hidden=false;$('#imageWatermarkAction').disabled=!hasImages;$('#imageGrayscaleAction').disabled=!hasImages;$('#applyImageColor').disabled=!hasImages;$('#cancelImageColor').disabled=!colorPreviewState;$('#videoToolSection').hidden=!videos.length;$('#videoCompressAction').disabled=videos.length!==1;$('#imageCopyAction').disabled=!copyable;$('#sourceMediaSave').disabled=!sourceReady;$('#sourceMediaSaveAs').disabled=!sourceReady;$('#exportImages').disabled=!targets.length;const sourceHint=sourceReady?'将处理结果写回所选媒体所属的 Office 文件':'请先选择媒体并完成加水印、调色或视频压缩';$('#sourceMediaSave').title=sourceHint;$('#sourceMediaSaveAs').title=sourceHint;$('#imageWorkspace').classList.toggle('preview-hidden',!single);if(single){activePreviewImageId=targets[0].image.id;showImagePreview(activePreviewImageId);renderImageExecutionPlan(targets[0].image);}renderImageSelectionTray(targets);}
function renderImageSelectionTray(targets=selectedImageTargets()){const tray=$('#imageSelectionTray'),visible=targets.slice(0,16),remaining=targets.length-visible.length;tray.hidden=!targets.length;tray.innerHTML=targets.length?`<strong>本次操作</strong><div>${visible.map(({file,image})=>`<button type="button" data-preview-selected="${esc(image.id)}" title="${esc(file.name)} · ${esc(image.name)}"><b>${esc(image.ext.toUpperCase())}</b><span>${esc(image.name)}</span><i data-remove-selected="${esc(image.id)}">×</i></button>`).join('')}${remaining?`<span class="selection-overflow">另有 ${remaining} 项已选</span>`:''}</div>`:'';$$('[data-preview-selected]').forEach(button=>button.onclick=event=>{const id=button.dataset.previewSelected;if(event.target.closest('[data-remove-selected]')){const target=findImageTarget(id);if(target){target.image.selected=false;target.file.batchSelected=false;const card=$(`[data-image-card="${CSS.escape(id)}"]`),box=card?.querySelector('[data-image-select]');if(card)card.classList.remove('selected');if(box)box.checked=false;updateCurrentGallerySelectionState();updateImageActionState();}return;}showImagePreview(id);});}
function updateCurrentGallerySelectionState(){const images=imageSourceFiles[activeImageFileIndex]?.images||[],selected=images.filter(image=>image.selected);$('#imageGalleryCount').textContent=`${images.length} 项媒体 · 已选 ${selected.length} 项`;$('#imageSelectAll').checked=Boolean(images.length)&&selected.length===images.length;$('#imageSelectAll').indeterminate=selected.length>0&&selected.length<images.length;}
function renderImageWorkspace(){
  const total=imageSourceFiles.reduce((sum,file)=>sum+file.images.length,0),selectedFiles=imageSourceFiles.filter(file=>file.batchSelected),file=imageSourceFiles[activeImageFileIndex],visible=imageSourceFiles.map((source,index)=>({source,index}));
  $('#imageSummary').textContent=`${imageSourceFiles.length} 个文件 · ${total} 项内置媒体 · 图片和视频均可预览、选择与导出`;
  $('#imageFileCount').textContent=`${imageSourceFiles.length} 个`;
  $('#imageFileSelectAll').checked=Boolean(imageSourceFiles.length)&&selectedFiles.length===imageSourceFiles.length;
  $('#imageFileSelectAll').indeterminate=selectedFiles.length>0&&selectedFiles.length<imageSourceFiles.length;
  $('#imageSourceList').innerHTML=visible.map(({source,index})=>`<div class="image-source-file ${index===activeImageFileIndex?'active':''}"><label title="选择整个文件用于批量操作"><input type="checkbox" data-image-file-select="${index}" ${source.batchSelected?'checked':''}></label><button data-image-source="${index}"><span class="file-type-icon">${extensionLabel(source)}</span><span><strong>${esc(source.name)}</strong><small>${esc(source.sourcePath)}</small><em>${source.error?'解析失败':`${source.images.length} 项媒体 · ${fmt(source.bytes)}`}</em></span></button></div>`).join('')||'<div class="image-filter-empty">没有符合筛选条件的文件</div>';
  $$('#imageSourceList [data-image-source]').forEach(button=>button.onclick=()=>{activeImageFileIndex=Number(button.dataset.imageSource);renderImageWorkspace();});
  $$('#imageSourceList [data-image-source]').forEach(button=>button.oncontextmenu=async event=>{event.preventDefault();const index=Number(button.dataset.imageSource),source=imageSourceFiles[index],action=await window.api.showFileContextMenu({filePath:source.sourcePath});if(action==='remove'){imageSourceFiles.splice(index,1);activeImageFileIndex=Math.min(activeImageFileIndex,Math.max(0,imageSourceFiles.length-1));renderImageWorkspace();}});
  $$('#imageSourceList [data-image-file-select]').forEach(input=>input.onchange=()=>{imageSourceFiles[Number(input.dataset.imageFileSelect)].batchSelected=input.checked;renderImageWorkspace();});
  renderImageGallery(file);updateImageActionState();if(activePreviewImageId){showImagePreview(activePreviewImageId);renderImageExecutionPlan(findImageTarget(activePreviewImageId)?.image);}
}
function renderImageGallery(file){
  const images=file?.images||[],selected=images.filter(image=>image.selected),types=[...new Set(images.map(image=>image.ext.toLowerCase()))].sort(),displayed=images.map((image,index)=>({image,index})).filter(({image})=>!imageFileTypeFilters.size||imageFileTypeFilters.has(image.ext.toLowerCase())).sort((a,b)=>imageFileSizeSort==='asc'?(a.image.bytes||0)-(b.image.bytes||0):imageFileSizeSort==='desc'?(b.image.bytes||0)-(a.image.bytes||0):a.index-b.index);
  $('#imageGalleryCount').textContent=file?.error?file.error:`${images.length} 项媒体 · 已选 ${selected.length} 项`;
  $('#imageSelectAll').checked=Boolean(images.length)&&selected.length===images.length;
  $('#imageSelectAll').indeterminate=selected.length>0&&selected.length<images.length;
  $('#clearImageEffects').hidden=!images.some(image=>image.processedData);
  $('#imageFileFilters').innerHTML=`<div><strong>类型</strong>${types.map(type=>`<label><input type="checkbox" data-image-type-filter="${esc(type)}" ${imageFileTypeFilters.has(type)?'checked':''}>${esc(type)}</label>`).join('')}</div><label class="image-file-sort">大小<select id="imageFileSizeSort"><option value="default">默认</option><option value="desc" ${imageFileSizeSort==='desc'?'selected':''}>大到小</option><option value="asc" ${imageFileSizeSort==='asc'?'selected':''}>小到大</option></select></label>`;
  const gallery=$('#imageGallery'),loader=$('#imageGalleryLoad'),version=++galleryRenderVersion,batchSize=24;
  galleryObserver?.disconnect();galleryObserver=null;gallery.replaceChildren();loader.hidden=!displayed.length;loader.querySelector('progress').value=0;loader.querySelector('span').textContent=`正在准备 ${displayed.length} 项媒体`;
  const cardMarkup=({image,index})=>`<article class="image-card ${image.selected?'selected':''}" data-image-card="${esc(image.id)}" title="单击选择 · 双击放大 · 右键更多"><label><input type="checkbox" data-image-select="${index}" ${image.selected?'checked':''}><span>选择</span></label><div class="image-preview"><span class="media-format-badge">${esc(image.ext.toUpperCase())}</span><div class="media-thumb-shell" data-lazy-media="${esc(image.id)}"><span class="media-thumb-loading">${image.mediaType==='video'?'视频':'加载中'}</span></div>${image.processedData?`<b>${esc((image.effects||[]).join('、')||'已处理')}</b>`:''}</div><div class="image-card-meta"><strong>${esc(image.name)}</strong><small>${esc(image.entryPath)}</small><span>${image.width&&image.height?`${image.width} × ${image.height} · `:''}${fmt(image.bytes)} · ${image.mediaType==='video'?'视频':'图片'}</span>${image.processedData?`<em>处理：${esc((image.effects||[]).join('、'))}</em>`:''}</div></article>`;
  const hydrate=node=>{if(node.dataset.loaded)return;const target=findImageTarget(node.dataset.lazyMedia);if(!target)return;node.dataset.loaded='true';if(target.image.mediaType==='video'){node.innerHTML=`<div class="video-thumb"><b>▶</b><span>${esc(target.image.ext.toUpperCase())}</span></div>`;return;}if(!target.image.previewable){node.innerHTML='<div class="image-unavailable">可原样导出<br>暂不支持预览</div>';return;}const image=new Image();image.loading='lazy';image.decoding='async';image.alt=target.image.name;image.onload=()=>node.classList.add('loaded');image.onerror=()=>{node.innerHTML='<div class="image-unavailable">缩略图加载失败</div>';};image.src=imageDataUrl(target.image);node.replaceChildren(image);};
  galleryObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){hydrate(entry.target);galleryObserver?.unobserve(entry.target);}}),{root:gallery,rootMargin:'320px'});
  let cursor=0;const appendBatch=()=>{if(version!==galleryRenderVersion)return;const fragment=document.createDocumentFragment(),limit=Math.min(cursor+batchSize,displayed.length);for(;cursor<limit;cursor++){const template=document.createElement('template');template.innerHTML=cardMarkup(displayed[cursor]);fragment.append(template.content.firstElementChild);}gallery.append(fragment);gallery.querySelectorAll('[data-lazy-media]:not([data-observed])').forEach(node=>{node.dataset.observed='true';galleryObserver.observe(node);});const percent=displayed.length?Math.round(cursor/displayed.length*100):100;loader.querySelector('progress').value=percent;loader.querySelector('span').textContent=`已加载 ${cursor}/${displayed.length} 项`;if(cursor<displayed.length){(window.requestIdleCallback||((callback)=>setTimeout(callback,0)))(appendBatch,{timeout:80});}else loader.hidden=true;};
  if(displayed.length)requestAnimationFrame(appendBatch);else gallery.innerHTML='<div class="empty-state"><div><strong>没有符合条件的媒体</strong><p>可调整类型筛选或切换其他文件。</p></div></div>';
  $$('[data-image-type-filter]').forEach(input=>input.onchange=()=>{input.checked?imageFileTypeFilters.add(input.dataset.imageTypeFilter):imageFileTypeFilters.delete(input.dataset.imageTypeFilter);renderImageWorkspace();});
  $('#imageFileSizeSort').onchange=event=>{imageFileSizeSort=event.target.value;renderImageWorkspace();};
  gallery.onchange=event=>{const input=event.target.closest('[data-image-select]');if(!input)return;const image=images[Number(input.dataset.imageSelect)];image.selected=input.checked;input.closest('.image-card').classList.toggle('selected',input.checked);updateCurrentGallerySelectionState();updateImageActionState();};
  gallery.onclick=event=>{const card=event.target.closest('.image-preview')?.closest('[data-image-card]');if(!card)return;clearTimeout(galleryClickTimer);galleryClickTimer=setTimeout(()=>{const target=findImageTarget(card.dataset.imageCard);if(target){selectOnlyMedia(target);activePreviewImageId=target.image.id;}},180);};
  gallery.ondblclick=event=>{const card=event.target.closest('[data-image-card]');if(!card)return;clearTimeout(galleryClickTimer);const target=findImageTarget(card.dataset.imageCard);if(target)window.api.openMediaPreview({name:target.image.name,mime:target.image.mime,source:imageDataUrl(target.image)});};
  gallery.oncontextmenu=async event=>{const card=event.target.closest('[data-image-card]');if(!card)return;event.preventDefault();clearTimeout(galleryClickTimer);const target=findImageTarget(card.dataset.imageCard);if(!target)return;if(!target.image.selected)selectOnlyMedia(target);const targets=selectedImageTargets(),action=await window.api.showThumbnailContextMenu({selectedCount:targets.length});if(action==='copy-current')await copyImageTargets([target]);if(action==='copy-selected')await copyImageTargets(targets);if(action==='save-current'){selectOnlyMedia(target);await exportSelectedMedia(false);}if(action==='package-selected')await exportSelectedMedia(true);};
}
function showImagePreview(id){const target=findImageTarget(id);if(!target||!target.image.previewable)return;activePreviewImageId=id;const version=++previewLoadVersion,{file,image}=target,effects=(image.effects||[]).join('、'),badge=`<span class="media-format-badge">${esc(image.ext.toUpperCase())}</span>`,actions=image.mediaType==='video'?`<div class="preview-media-actions"><button data-preview-edit="compress">压缩视频</button>${image.processedPath?`<button data-preview-edit="copy-processed">复制压缩视频（${fmt(image.bytes)} → ${fmt(image.processedBytes)}）</button>`:''}<button data-preview-edit="save-as">另存为</button></div>`:`<div class="preview-media-actions"><button data-preview-edit="watermark">加水印</button><button data-preview-edit="grayscale">转黑白</button><button data-preview-edit="copy">复制</button><button data-preview-edit="save-as">另存为</button></div>`,content=$('#imagePreviewContent'),loader=$('#imagePreviewLoader');$('#imagePreviewPane').classList.add('visible');content.hidden=true;loader.hidden=false;requestAnimationFrame(()=>setTimeout(()=>{if(version!==previewLoadVersion)return;content.className='image-preview-content';content.innerHTML=image.mediaType==='video'?`<section><header><strong>原始视频</strong><small>${esc(file.name)} · ${esc(image.name)}</small></header><div>${badge}${mediaMarkup(image,{original:true,controls:true})}</div></section><section><header><strong>${image.processedPath?'压缩后':'导出结果'}</strong><small>${effects||'视频保持原始格式与内容'}</small></header><div class="video-process-note">${badge}${image.processedPath?mediaMarkup(image,{controls:true}):'<strong>尚未压缩</strong><span>可以配置码率后生成压缩视频。</span>'}</div></section>${actions}`:`<section><header><strong>原图</strong><small>${esc(file.name)} · ${esc(image.name)}</small></header><div>${badge}${mediaMarkup(image,{original:true})}</div></section><section><header><strong>处理后</strong><small>${effects?esc(effects):'尚未处理，与原图一致'}</small></header><div>${badge}${mediaMarkup(image)}</div></section>${actions}`;const media=[...content.querySelectorAll('img,video')];let pending=media.length;const ready=()=>{if(version!==previewLoadVersion)return;if(--pending<=0){loader.hidden=true;content.hidden=false;}};if(!pending){loader.hidden=true;content.hidden=false;}else media.forEach(node=>{if(node.tagName==='IMG'&&node.complete)ready();else{node.addEventListener(node.tagName==='VIDEO'?'loadeddata':'load',ready,{once:true});node.addEventListener('error',ready,{once:true});}});$$('[data-preview-edit]').forEach(button=>button.onclick=()=>handleMediaAction(button.dataset.previewEdit,target));},0));}
function closeImagePreview(){activePreviewImageId='';previewLoadVersion++;$('#imagePreviewPane').classList.remove('visible');$('#imagePreviewLoader').hidden=true;$('#imagePreviewContent').hidden=false;$('#imagePreviewContent').className='image-preview-empty';$('#imagePreviewContent').innerHTML='单击相册中的媒体<br>查看原始内容和处理后效果';renderImageExecutionPlan(null);}
function loadCanvasImage(source){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('图片无法解码'));image.src=source;});}
function imagePlanLabel(options){if(options.grayscale)return '转为黑白';if(options.adjustment){const value=options.adjustment;return `调色 · ${value.grayscale?'黑白 · ':''}对比度 ${value.contrast}% · 饱和度 ${value.saturation}%`;}if(options.tone)return `调色 · 对比度 ${options.tone.contrast}% · 饱和度 ${options.tone.saturation}%`;const watermark=options.watermark;if(!watermark)return '媒体处理';const direction={horizontal:'横向',vertical:'竖向',diagonal:'斜向'}[watermark.direction]||watermark.direction;return `${watermark.kind==='image'?'图片水印':`文字水印“${watermark.text}”`} · ${direction} · ${Math.round(watermark.opacity*100)}%`;}
async function transformTone(image,{contrast=100,saturation=100}){const source=await loadCanvasImage(imageDataUrl(image)),canvas=document.createElement('canvas');canvas.width=source.naturalWidth;canvas.height=source.naturalHeight;const context=canvas.getContext('2d');context.filter=`contrast(${contrast}%) saturate(${saturation}%)`;context.drawImage(source,0,0);image.effects=image.effects||[];image.effects.push(`调色（对比度 ${contrast}% · 饱和度 ${saturation}%）`);const preferred=['image/png','image/jpeg','image/webp'].includes(image.mime)?image.mime:'image/png';image.processedData=canvas.toDataURL(preferred,preferred==='image/jpeg'?.92:undefined);image.processedMime=image.processedData.slice(5,image.processedData.indexOf(';'));image.processedName=image.name;}
async function transformAdjustment(image,{grayscale=false,contrast=100,saturation=100},preview=false){const source=await loadCanvasImage(imageDataUrl(image)),canvas=document.createElement('canvas');canvas.width=source.naturalWidth;canvas.height=source.naturalHeight;const context=canvas.getContext('2d');context.filter=`${grayscale?'grayscale(1) ':''}contrast(${contrast}%) saturate(${saturation}%)`;context.drawImage(source,0,0);image.effects=image.effects||[];image.effects.push(`${preview?'预览：':''}${imagePlanLabel({adjustment:{grayscale,contrast,saturation}})}`);const preferred=['image/png','image/jpeg','image/webp'].includes(image.mime)?image.mime:'image/png';image.processedData=canvas.toDataURL(preferred,preferred==='image/jpeg'?.92:undefined);image.processedMime=image.processedData.slice(5,image.processedData.indexOf(';'));image.processedName=image.name;}
function colorSettings(){return{grayscale:$('#imageGrayscaleAction').checked,contrast:Number($('#imageContrast').value),saturation:Number($('#imageSaturation').value)};}
function restoreColorPreview(){if(!colorPreviewState)return;colorPreviewVersion++;const{image,values}=colorPreviewState;for(const[key,state]of Object.entries(values)){if(state.exists)image[key]=state.value;else delete image[key];}colorPreviewState=null;$('#cancelImageColor').disabled=true;}
function resetColorControls(){ $('#imageGrayscaleAction').checked=false;$('#imageContrast').value=100;$('#imageSaturation').value=100;$('#contrastValue').textContent='100%';$('#saturationValue').textContent='100%';}
async function previewColorAdjustment(){const targets=selectedImageTargets().filter(({image})=>image.processable);if(targets.length!==1)return;const image=targets[0].image,keys=['processedData','processedMime','processedName','effects'];if(colorPreviewState?.image.id!==image.id){restoreColorPreview();colorPreviewState={image,values:Object.fromEntries(keys.map(key=>[key,{exists:Object.hasOwn(image,key),value:structuredClone(image[key])}]))};}else{const values=colorPreviewState.values;for(const[key,state]of Object.entries(values)){if(state.exists)image[key]=structuredClone(state.value);else delete image[key];}}const version=++colorPreviewVersion;await transformAdjustment(image,colorSettings(),true);if(version!==colorPreviewVersion)return;$('#cancelImageColor').disabled=false;showImagePreview(image.id);}
async function rebuildImagePlan(image){delete image.processedData;delete image.processedMime;delete image.processedName;delete image.effects;for(const operation of image.planOperations||[]){if(operation.options?.adjustment)await transformAdjustment(image,operation.options.adjustment);else if(operation.options?.tone)await transformTone(image,operation.options.tone);else await transformImage(image,operation.options);}}
function renderImageExecutionPlan(image){const panel=$('#imageExecutionPlan'),operations=image?.planOperations||[];$('#imagePlanCount').textContent=operations.length;panel.querySelector(':scope > div').innerHTML=operations.length?operations.map((operation,index)=>`<div class="image-plan-row"><span>${index+1}</span><div><strong>${esc(operation.label)}</strong><small>${operation.kind==='video-compress'?'待处理 · 暂不支持实时预览':'已在处理后预览中实时呈现'}</small></div><button type="button" data-remove-image-plan="${esc(operation.id)}" aria-label="删除步骤">×</button></div>`).join(''):'<p>尚未添加处理步骤</p>';$$('[data-remove-image-plan]').forEach(button=>button.onclick=async()=>{const operationIndex=operations.findIndex(operation=>operation.id===button.dataset.removeImagePlan);if(operationIndex<0)return;operations.splice(operationIndex,1);if(image.mediaType==='video'){delete image.processedPath;delete image.processedUrl;delete image.processedBytes;delete image.processedName;delete image.effects;}else await rebuildImagePlan(image);renderImageWorkspace();});}
async function transformImage(image,{grayscale=false,watermark=null}={}){const source=await loadCanvasImage(imageDataUrl(image)),canvas=document.createElement('canvas');canvas.width=source.naturalWidth;canvas.height=source.naturalHeight;const context=canvas.getContext('2d');context.drawImage(source,0,0);image.effects=image.effects||[];if(grayscale){const pixels=context.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<pixels.data.length;i+=4){const gray=Math.round(pixels.data[i]*.299+pixels.data[i+1]*.587+pixels.data[i+2]*.114);pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=gray;}context.putImageData(pixels,0,0);if(!image.effects.includes('黑白化'))image.effects.push('黑白化');}if(watermark){context.save();context.globalAlpha=watermark.opacity;context.translate(canvas.width/2,canvas.height/2);context.rotate(watermark.direction==='vertical'?-Math.PI/2:watermark.direction==='diagonal'?-Math.PI/4:0);if(watermark.kind==='image'){const mark=await loadCanvasImage(watermark.image);const width=canvas.width*.42,height=mark.naturalHeight/mark.naturalWidth*width;context.drawImage(mark,-width/2,-height/2,width,height);}else{const size=Math.max(18,Math.round(Math.min(canvas.width,canvas.height)*.11));context.font=`700 ${size}px "Segoe UI",sans-serif`;context.textAlign='center';context.textBaseline='middle';context.fillStyle='#ffffff';context.strokeStyle='rgba(0,0,0,.38)';context.lineWidth=Math.max(2,size*.035);context.strokeText(watermark.text,0,0);context.fillText(watermark.text,0,0);}context.restore();const direction={horizontal:'横向',vertical:'竖向',diagonal:'斜向'}[watermark.direction],description=watermark.kind==='image'?`图片水印（${direction}，${Math.round(watermark.opacity*100)}%）`:`文字水印“${watermark.text}”（${direction}，${Math.round(watermark.opacity*100)}%）`;image.effects.push(description);}const preferred=['image/png','image/jpeg','image/webp'].includes(image.mime)?image.mime:'image/png';image.processedData=canvas.toDataURL(preferred,preferred==='image/jpeg'?.92:undefined);image.processedMime=image.processedData.slice(5,image.processedData.indexOf(';'));const extension=image.processedMime==='image/jpeg'?'.jpg':image.processedMime==='image/webp'?'.webp':'.png';image.processedName=image.name.replace(/\.[^.]+$/, '')+extension;}
async function applyImageTransform(options){const targets=selectedImageTargets().filter(({image})=>image.processable);if(!targets.length){alert('所选内容没有可处理的图片。视频以及 EMF、WMF、TIFF 可原样导出，但不参与水印和黑白处理。');return;}const operation=imagePlanLabel(options);beginMediaTask(`正在${operation}`,`$ canvas-process --operation "${operation}" --count ${targets.length}`);setStatus(`正在处理 ${targets.length} 张图片`);for(let index=0;index<targets.length;index++){const {image}=targets[index];updateMediaTask(index/targets.length*100,`[${index+1}/${targets.length}] ${image.name} · ${operation}`);await transformImage(image,options);image.planOperations=image.planOperations||[];image.planOperations.push({id:`plan-${Date.now()}-${index}`,label:operation,options:structuredClone(options)});}updateMediaTask(100,`DONE · 已处理 ${targets.length} 张图片`);renderImageWorkspace();setStatus(`图片处理完成 · ${targets.length} 张`);}
function selectOnlyMedia(target){for(const file of imageSourceFiles){file.batchSelected=false;for(const image of file.images)image.selected=image.id===target.image.id;}activeImageFileIndex=Math.max(0,imageSourceFiles.indexOf(target.file));renderImageWorkspace();}
function updateCompressionEstimate(){if(!activeCompressionTarget?.image.probe)return;const info=activeCompressionTarget.image.probe,video=Math.max(64,Number($('#videoBitrate').value)||0),audio=Math.max(16,Number($('#audioBitrate').value)||0),bytes=Math.round(info.duration*(video+audio)*1000/8),low=video<2095||audio<128;$('#videoEstimatedSize').textContent=`${fmt(info.bytes)} → 约 ${fmt(bytes)}`;$('#videoCompressionWarning').textContent=low?'低于建议质量（视频 2095 kbps / 音频 128 kbps），仍允许继续。':bytes>=info.bytes?'当前设置预计不会缩小文件，可降低码率。':'保持原始分辨率，按目标码率估算。';$('#videoCompressionWarning').classList.toggle('warning',low);}
async function openVideoCompression(target,ratio=0){selectOnlyMedia(target);activeCompressionTarget=target;$('#videoCompressionPanel').hidden=false;$('#imageEffectPanel').hidden=true;$('#runVideoCompression').disabled=false;$('#videoCompressionSource').textContent='正在读取视频时长和码率…';$('#videoEstimatedSize').textContent='—';beginMediaTask(`正在分析 ${target.image.name}`,`$ ffprobe "${target.file.sourcePath} :: ${target.image.entryPath}"`);try{const probe=await window.api.probeOfficeVideo({sourcePath:target.file.sourcePath,entryPath:target.image.entryPath});target.image.probe=probe;let video=2095,audio=128;if(ratio){const total=probe.duration?probe.bytes*ratio*8/probe.duration/1000:2223;video=Math.max(64,Math.round(total-audio));}$('#videoBitrate').value=video;$('#audioBitrate').value=audio;$('#videoCompressionSource').textContent=`${target.image.name} · ${probe.width}×${probe.height} · ${probe.duration.toFixed(1)} 秒 · 当前 ${fmt(probe.bytes)}`;updateCompressionEstimate();updateMediaTask(100,`INFO · ${probe.videoCodec}/${probe.audioCodec} · ${probe.sourceBitrate} kbps`);}catch(error){$('#videoCompressionSource').textContent=`读取失败：${error.message}`;$('#runVideoCompression').disabled=true;updateMediaTask(0,`ERROR · ${error.message}`);}}
async function handleMediaAction(action,target){if(action==='watermark'){selectOnlyMedia(target);$('#watermarkToolSection').open=true;$('#imageEffectPanel').hidden=false;refreshWatermarkTime();return;}if(action==='grayscale'){selectOnlyMedia(target);await applyImageTransform({grayscale:true});return;}if(action==='compress'||action==='compress-default'){await openVideoCompression(target);return;}if(action.startsWith('compress-')){await openVideoCompression(target,Number(action.slice(9)));return;}if(action==='copy'){await copyImageTargets([target]);return;}if(action==='copy-processed'&&target.image.processedPath){await window.api.copyMediaFile(target.image.processedPath);setStatus(`已复制压缩视频 · ${fmt(target.image.bytes)} → ${fmt(target.image.processedBytes)}`);return;}if(action==='save-as'){selectOnlyMedia(target);await exportSelectedMedia('saveAs');}}
async function addImageSourceFiles(){const selected=await window.api.pickImageSourceFiles(),existing=new Set(imageSourceFiles.map(file=>file.sourcePath)),incoming=selected.filter(file=>!existing.has(file));if(!incoming.length)return;setStatus('正在提取新增文件图片');const inspected=await window.api.inspectOfficeImages(incoming);imageSourceFiles.push(...inspected);activeImageFileIndex=imageSourceFiles.length-inspected.length;renderImageWorkspace();setStatus(`已添加 ${inspected.length} 个文件`);}
$('#addImageFiles').onclick=addImageSourceFiles;
$('#imageFileSelectAll').onchange=event=>{imageSourceFiles.forEach(file=>file.batchSelected=event.target.checked);renderImageWorkspace();};
$('#imageSelectAll').onchange=event=>{const checked=event.target.checked;(imageSourceFiles[activeImageFileIndex]?.images||[]).forEach(image=>image.selected=checked);$$('#imageGallery [data-image-card]').forEach(card=>card.classList.toggle('selected',checked));$$('#imageGallery [data-image-select]').forEach(input=>input.checked=checked);updateCurrentGallerySelectionState();updateImageActionState();};
$('#imageGrayscaleAction').onchange=previewColorAdjustment;
$('#imageContrast').oninput=event=>{$('#contrastValue').textContent=`${event.target.value}%`;previewColorAdjustment();};
$('#imageSaturation').oninput=event=>{$('#saturationValue').textContent=`${event.target.value}%`;previewColorAdjustment();};
$('#cancelImageColor').onclick=()=>{restoreColorPreview();resetColorControls();$('#colorToolSection').open=false;renderImageWorkspace();setStatus('已取消调色预览');};
$('#applyImageColor').onclick=async()=>{const targets=selectedImageTargets().filter(({image})=>image.processable),adjustment=colorSettings(),label=imagePlanLabel({adjustment});if(!targets.length)return;if(!adjustment.grayscale&&adjustment.contrast===100&&adjustment.saturation===100){restoreColorPreview();$('#colorToolSection').open=false;setStatus('调色参数未发生变化');return;}restoreColorPreview();beginMediaTask('正在应用调色',`$ canvas-process --operation "${label}" --count ${targets.length}`);for(let index=0;index<targets.length;index++){const {image}=targets[index];await transformAdjustment(image,adjustment);image.planOperations=image.planOperations||[];image.planOperations.push({id:`plan-${Date.now()}-${index}`,label,options:{adjustment}});updateMediaTask((index+1)/targets.length*100,`[${index+1}/${targets.length}] ${image.name} · ${label}`);}resetColorControls();$('#colorToolSection').open=false;renderImageWorkspace();setStatus(`调色步骤已应用 · ${targets.length} 张`);};
$('#imageWatermarkAction').onclick=()=>{$('#watermarkToolSection').open=true;$('#imageEffectPanel').hidden=false;refreshWatermarkTime();};
$('#videoCompressAction').onclick=()=>{const [target]=selectedImageTargets().filter(({image})=>image.mediaType==='video');if(target)openVideoCompression(target);};
$('#closeImageEffect').onclick=$('#cancelImageEffect').onclick=()=>{$('#watermarkToolSection').open=false;setStatus('已取消水印设置');};
$('#watermarkKind').onchange=event=>{$('#watermarkTextRow').hidden=event.target.value!=='text';$('#watermarkImageRow').hidden=event.target.value!=='image';};
$('#refreshWatermarkTime').onclick=refreshWatermarkTime;
$('#watermarkToolSection').ontoggle=event=>{if(event.currentTarget.open)refreshWatermarkTime();};
refreshWatermarkTime();
$('#watermarkOpacity').oninput=event=>{$('#watermarkOpacityValue').textContent=`${event.target.value}%`;};
$('#chooseWatermarkImage').onclick=async()=>{const selected=await window.api.pickWatermarkImage();if(!selected)return;watermarkImage=selected;$('#watermarkImageName').textContent=watermarkImage.name;const preview=$('#watermarkImagePreview');preview.src=watermarkImage.data;preview.hidden=false;};
$('#applyImageWatermark').onclick=async()=>{const kind=$('#watermarkKind').value;if(kind==='image'&&!watermarkImage){alert('请先选择水印图片。');return;}const text=$('#watermarkText').value.trim();if(kind==='text'&&!text){alert('请输入水印文字。');return;}await applyImageTransform({watermark:{kind,text,image:watermarkImage?.data,direction:$('#watermarkDirection').value,opacity:Number($('#watermarkOpacity').value)/100}});$('#watermarkToolSection').open=false;};
$('#videoBitrate').oninput=$('#audioBitrate').oninput=updateCompressionEstimate;
$('#cancelVideoCompression').onclick=()=>{$('#videoCompressionPanel').hidden=true;activeCompressionTarget=null;};
$('#runVideoCompression').onclick=async()=>{const target=activeCompressionTarget;if(!target)return;$('#videoCompressionPanel').hidden=true;$('#mediaTaskTerminal').textContent='';$('#mediaTaskProgress').value=0;$('#mediaTaskLabel').textContent=`正在压缩 ${target.image.name}`;$('#mediaTaskPercent').textContent='0%';setStatus(`正在压缩 ${target.image.name}`);try{const result=await window.api.compressOfficeVideo({sourcePath:target.file.sourcePath,entryPath:target.image.entryPath,videoKbps:Number($('#videoBitrate').value),audioKbps:Number($('#audioBitrate').value)});target.image.processedPath=result.outputPath;target.image.processedUrl=result.outputUrl;target.image.processedBytes=result.bytes;target.image.processedName=target.image.name.replace(/\.[^.]+$/, '')+'-压缩.mp4';const label=`视频压缩 ${result.videoKbps}k/${result.audioKbps}k（${fmt(result.bytes)}）`;target.image.effects=[...(target.image.effects||[]).filter(item=>!item.startsWith('视频压缩')),label];target.image.planOperations=[...(target.image.planOperations||[]).filter(item=>item.kind!=='video-compress'),{id:`plan-${Date.now()}`,kind:'video-compress',label}];renderImageWorkspace();showImagePreview(target.image.id);renderImageExecutionPlan(target.image);setStatus(`视频压缩完成 · ${fmt(result.bytes)}（原 ${fmt(target.image.bytes)}）`);}catch(error){$('#mediaTaskLabel').textContent='视频压缩失败';$('#mediaTaskPercent').textContent='需检查';$('#mediaTaskTerminal').textContent+=`ERROR: ${error.message}\n`;setStatus('视频压缩失败');}};
$('#clearImageEffects').onclick=()=>{for(const image of imageSourceFiles[activeImageFileIndex]?.images||[]){delete image.processedData;delete image.processedMime;delete image.processedName;delete image.processedPath;delete image.processedUrl;delete image.processedBytes;delete image.effects;delete image.planOperations;}renderImageWorkspace();};
async function copyImageTargets(targets=selectedImageTargets()){if(targets.length===1&&targets[0].image.processedPath){await window.api.copyMediaFile(targets[0].image.processedPath);setStatus(`已复制压缩视频 · ${fmt(targets[0].image.bytes)} → ${fmt(targets[0].image.processedBytes)}`);return;}const payload=imageCopyPayload(targets);if(!payload.length){setStatus('所选内容暂不支持直接复制，可使用另存为');return;}const result=await window.api.copyOfficeImages({images:payload});setStatus(`已复制 ${result.count} 张图片`);}
$('#imageCopyAction').onclick=()=>copyImageTargets();
$('#closeImagePreview').onclick=closeImagePreview;
$('#imagePreviewContent').oncontextmenu=async event=>{event.preventDefault();const target=activePreviewImageId?findImageTarget(activePreviewImageId):null;if(!target)return;const action=await window.api.showMediaContextMenu({mediaType:target.image.mediaType,bytes:target.image.bytes,processedBytes:target.image.processedBytes||0,hasProcessed:Boolean(target.image.processedPath)});if(action)await handleMediaAction(action,target);};
document.addEventListener('keydown',event=>{if(!(event.ctrlKey||event.metaKey)||event.key.toLowerCase()!=='c'||$('#imageWorkspace').hidden||/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName))return;const targets=selectedImageTargets(),preview=activePreviewImageId?findImageTarget(activePreviewImageId):null;if(targets.length||preview){event.preventDefault();copyImageTargets(targets.length?targets:[preview]);}});
async function exportSelectedMedia(forceArchive=true){const targets=selectedImageTargets();if(!targets.length)return;const sourceNames=[...new Set(targets.map(({file})=>file.name))],images=targets.map(({file,image})=>({folder:sourceNames.length>1?file.name:'',name:image.processedName||image.name,path:image.processedPath||'',data:image.processedPath?'':image.processedData?image.processedData.split(',')[1]:image.data})),archiveName=sourceNames.length===1?sourceNames[0]:'PreSalesX-提取媒体',result=await window.api.exportOfficeImages({images,archiveName,forceArchive});if(result){setStatus(`${forceArchive?'已打包下载':'已另存'} ${result.count} 项媒体`);window.api.showFile(result.destination);}}
function sourceMediaRequests(){const grouped=new Map();for(const {file,image} of processedSourceTargets()){if(!grouped.has(file.sourcePath))grouped.set(file.sourcePath,[]);grouped.get(file.sourcePath).push({entryPath:image.entryPath,path:image.processedPath||'',data:image.processedPath?'':image.processedData.split(',')[1]});}return[...grouped].map(([sourcePath,replacements])=>({sourcePath,replacements}));}
async function saveProcessedSources(action){const requests=sourceMediaRequests();if(!requests.length){alert('所选媒体没有可写回源文件的同格式处理结果。GIF 或改变容器格式的视频请使用“打包下载”。');return;}setStatus(action==='save'?'正在保存源文件':'正在另存源文件');const result=await window.api.saveOfficeMediaSources({requests,action});if(!result){setStatus('已取消另存为');return;}if(action==='save'){const refreshed=await window.api.inspectOfficeImages(requests.map(request=>request.sourcePath));for(const next of refreshed){const index=imageSourceFiles.findIndex(file=>file.sourcePath===next.sourcePath);if(index>=0)imageSourceFiles[index]=next;}activePreviewImageId='';renderImageWorkspace();closeImagePreview();}setStatus(`已${action==='save'?'保存':'另存'} ${result.count} 个源文件`);if(result.destination)window.api.showFile(result.destination);}
$('#exportImages').onclick=exportSelectedMedia;
$('#sourceMediaSave').onclick=()=>saveProcessedSources('save');
$('#sourceMediaSaveAs').onclick=()=>saveProcessedSources('saveAs');
$('#toggleMediaTerminal').onclick=()=>{const terminal=$('#mediaTaskTerminal'),open=terminal.hidden;terminal.hidden=!open;$('#toggleMediaTerminal i').textContent=open?'⌄':'⌃';};

function renderSanitizationWorkspace(){
  const selected=sanitizationFiles.filter(file=>file.batchSelected);
  $('#sanitizeFileCount').textContent=`${sanitizationFiles.length} 个`;
  $('#clearSanitizeFiles').disabled=!sanitizationFiles.length;
  $('#sanitizeSelectedCount').textContent=`已选择 ${selected.length} 个文件`;
  $('#sanitizeBatchActions').hidden=!selected.length;
  $('#sanitizeSelectAll').checked=Boolean(sanitizationFiles.length)&&selected.length===sanitizationFiles.length;
  $('#sanitizeSelectAll').indeterminate=selected.length>0&&selected.length<sanitizationFiles.length;
  $('#sanitizeFileList').innerHTML=sanitizationFiles.map((file,index)=>`<div class="sanitize-file ${index===activeSanitizationIndex?'active':''}"><label class="sanitize-file-check" title="选择用于批量操作"><input type="checkbox" data-sanitize-select="${index}" ${file.batchSelected?'checked':''}></label><button type="button" data-sanitize-file="${index}"><span class="file-type-icon">${extensionLabel(file)}</span><span class="sanitize-file-copy"><strong>${esc(file.name)}</strong><small>${esc(file.sourcePath)}</small><span>${file.error?'解析失败':`${file.items.length} 项可脱敏${file.hasRevisions?' · 修订中':''}`}</span></span></button></div>`).join('');
  $$('#sanitizeFileList [data-sanitize-file]').forEach(button=>button.onclick=()=>{activeSanitizationIndex=Number(button.dataset.sanitizeFile);$('#watermarkResults').hidden=true;renderSanitizationWorkspace();});
  $$('#sanitizeFileList [data-sanitize-file]').forEach(button=>button.oncontextmenu=event=>{event.preventDefault();const index=Number(button.dataset.sanitizeFile),file=sanitizationFiles[index];showDocumentFileMenu(file.sourcePath,()=>{sanitizationFiles.splice(index,1);activeSanitizationIndex=Math.min(activeSanitizationIndex,Math.max(0,sanitizationFiles.length-1));renderSanitizationWorkspace();});});
  $$('#sanitizeFileList [data-sanitize-select]').forEach(input=>input.onchange=()=>{sanitizationFiles[Number(input.dataset.sanitizeSelect)].batchSelected=input.checked;renderSanitizationWorkspace();});
  renderSanitizationDetail();
}
async function addSanitizationFiles(){const selected=await window.api.pickWatermarkFiles(),existing=new Set(sanitizationFiles.map(file=>file.sourcePath)),incoming=selected.filter(file=>!existing.has(file));if(!incoming.length)return;setStatus('正在检查新增文件');const inspected=await window.api.inspectSanitization(incoming);sanitizationFiles.push(...inspected);activeSanitizationIndex=sanitizationFiles.length-inspected.length;renderSanitizationWorkspace();setStatus(`已添加 ${inspected.length} 个文件`);}
$('#sanitizeSelectAll').onchange=event=>{sanitizationFiles.forEach(file=>file.batchSelected=event.target.checked);renderSanitizationWorkspace();};
$('#clearSanitizeFiles').onclick=()=>{sanitizationFiles=[];activeSanitizationIndex=0;$('#watermarkResults').hidden=true;$('#revisionWarning').innerHTML='';renderSanitizationWorkspace();setStatus('已清空文件列表');};
function toggleFilePane(layoutSelector,button){const layout=$(layoutSelector),collapsed=layout.classList.toggle('files-collapsed'),label=collapsed?'展开文件栏':'折叠文件栏';button.textContent=collapsed?'›':'‹';button.title=label;button.setAttribute('aria-label',label);}
$('#toggleSanitizeFiles').onclick=event=>toggleFilePane('.sanitize-layout',event.currentTarget);
$('#toggleImageFiles').onclick=event=>toggleFilePane('.image-studio-layout',event.currentTarget);
$('#toggleEditorFiles').onclick=event=>toggleFilePane('.editor-layout',event.currentTarget);
function batchTargets(){return sanitizationFiles.filter(file=>file.batchSelected&&!file.error);}
$('#batchClearWatermarks').onclick=()=>{for(const file of batchTargets())for(const item of file.items.filter(item=>item.type==='watermark'))item.selected=true;renderSanitizationWorkspace();setStatus(`已为 ${batchTargets().length} 个文件标记清除水印，保存后生效`);};
$('#batchClearMetadata').onclick=()=>{for(const file of batchTargets())for(const item of file.items.filter(item=>item.type==='metadata')){if(item.originalValue===undefined)item.originalValue=item.detail||'';item.value='';}renderSanitizationWorkspace();setStatus(`已为 ${batchTargets().length} 个文件标记清除文件属性，保存后生效`);};
function renderSanitizationDetail(){
  const file=sanitizationFiles[activeSanitizationIndex];if(!file){$('#sanitizeComparisonList').innerHTML='';$('#sanitizeSave').disabled=true;$('#sanitizeSaveAs').disabled=true;return;}
  const byType=type=>file.items.filter(item=>item.type===type),watermarks=byType('watermark'),comments=byType('comment'),metadata=byType('metadata'),filesystem=byType('filesystem'),descriptionFields=new Set(['title','subject','keywords','category','comments']),description=metadata.filter(item=>descriptionFields.has(item.field)),origin=metadata.filter(item=>!descriptionFields.has(item.field)),editable=[...metadata,...filesystem];
  $('#revisionWarning').innerHTML=file.hasRevisions?`<div class="revision-warning"><strong>当前处于修订模式，建议打开源文件 → 审阅 → 接受所有修订</strong><span>检测到 ${file.revisionCount||0} 个修订标记；PreSalesX 不会擅自接受或拒绝修订。</span></div>`:'';
  for(const item of editable){if(item.originalValue===undefined)item.originalValue=item.detail||'';if(item.value===undefined)item.value=item.originalValue;}
  const itemHeading=item=>item.type==='watermark'?`<span class="sanitize-watermark-heading"><strong class="sanitize-item-name">${esc(item.label)}</strong><small><i aria-hidden="true">${item.subtype==='background'?'▧':item.subtype==='header'?'页':'T'}</i>${esc(item.detail||'未能读取水印内容')}</small></span>`:`<strong class="sanitize-item-name">${esc(item.label)}</strong>`;
  const comparisonRow=item=>{
    if(item.type==='metadata'||item.type==='filesystem'){const changed=String(item.value)!==String(item.originalValue),canClear=item.type==='metadata',cleared=canClear&&changed&&item.value==='',isTime=metadataTimeFields.has(item.field)||item.type==='filesystem',inputValue=isTime?toLocalDateTime(item.value):item.value,scope=item.type==='filesystem'?'filesystem':'metadata',formatHint=isTime?'保存时转换为 ISO 8601：YYYY-MM-DDTHH:mm:ss.sssZ':'';return `<div class="sanitize-compare-row sanitize-compare-item metadata-result ${changed?'changed':'kept'}" data-sanitize-row="${esc(item.id)}"><strong class="sanitize-item-name">${esc(item.label)}</strong><span class="sanitize-before-value"><small>${esc(item.originalValue||'<空>')}</small></span><span class="sanitize-after-value"><span class="sanitize-inline-controls"><span class="sanitize-editor"><input type="${isTime?'datetime-local':'text'}" ${isTime?'step="1" data-metadata-time="true"':''} data-${scope}-field="${esc(item.field)}" value="${esc(inputValue)}" placeholder="&lt;空&gt;" aria-label="${esc(item.label)}脱敏后的值" title="${formatHint}"></span><span class="sanitize-choice"><button type="button" class="${!changed?'selected':''}" data-restore-${scope}="${esc(item.field)}">保留原值</button>${canClear?`<button type="button" class="danger ${cleared?'selected':''}" data-clear-metadata="${esc(item.field)}">清空</button>`:''}</span><em>${cleared?'已清空':changed?'已修改':'保留'}</em></span></span></div>`;}
    return `<div class="sanitize-compare-row sanitize-compare-item ${item.selected?'changed':'kept'}" data-sanitize-row="${esc(item.id)}">${itemHeading(item)}<span class="sanitize-before-value"><small>${esc(item.detail||'<空>')}</small></span><span class="sanitize-after-value"><span class="sanitize-inline-controls"><small class="sanitize-result-preview">${item.selected?'&lt;已删除&gt;':esc(item.detail||'<空>')}</small><span class="sanitize-choice"><button type="button" class="${item.selected?'':'selected'}" data-set-removal="${esc(item.id)}" data-remove="false">保留</button><button type="button" class="danger ${item.selected?'selected':''}" data-set-removal="${esc(item.id)}" data-remove="true">删除</button></span><em>${item.selected?'将删除':'保留'}</em></span></span></div>`;
  };
  const group=(type,label,items)=>{const actions=type==='metadata'?'<button type="button" data-metadata-all="clear">全部清空</button><button type="button" data-metadata-all="restore">恢复全部</button>':type==='filesystem'?'<button type="button" data-filesystem-all="restore">恢复全部</button>':'<button type="button" data-removal-all="delete">全部删除</button><button type="button" data-removal-all="keep">全部保留</button>';return `<section class="sanitize-compare-group" data-sanitize-group="${type}"><header class="sanitize-compare-row"><strong>${label}<small>${items.length} 项</small></strong><span></span><span class="sanitize-group-actions">${items.length?actions:''}</span></header>${items.length?items.map(comparisonRow).join(''):'<p class="sanitize-none">未检测到此类内容</p>'}</section>`;};
  $('#sanitizeComparisonList').innerHTML=group('watermark','水印与背景',watermarks)+group('comment','批注',comments)+group('metadata','说明',description)+group('metadata','来源',origin)+group('filesystem','文件',filesystem);
  const changedItems=()=>file.items.filter(item=>item.type==='metadata'||item.type==='filesystem'?String(item.value)!==String(item.originalValue):item.selected);
  const updateControls=()=>{const changes=changedItems(),chosen=batchTargets(),targets=chosen.length?chosen:[file],totalChanges=targets.reduce((sum,target)=>sum+target.items.filter(item=>item.type==='metadata'||item.type==='filesystem'?String(item.value)!==String(item.originalValue):item.selected).length,0);$('#sanitizeChangeCount').textContent=chosen.length?`${chosen.length} 个文件 · ${totalChanges} 项变化`:`${changes.length} 项变化`;$('#sanitizeSave').disabled=!totalChanges||targets.some(target=>target.error);$('#sanitizeSaveAs').disabled=!totalChanges||targets.some(target=>target.error);};
  $$('[data-metadata-field],[data-filesystem-field]').forEach(input=>input.oninput=()=>{const scope=input.dataset.filesystemField?'filesystem':'metadata',field=input.dataset.filesystemField||input.dataset.metadataField,item=editable.find(value=>value.type===scope&&value.field===field),row=input.closest('[data-sanitize-row]'),nextValue=input.dataset.metadataTime?fromLocalDateTime(input.value):input.value,changed=String(nextValue)!==String(item.originalValue);item.value=nextValue;row.classList.toggle('changed',changed);row.classList.toggle('kept',!changed);row.querySelector(`[data-restore-${scope}]`).classList.toggle('selected',!changed);const clear=row.querySelector('[data-clear-metadata]');if(clear)clear.classList.toggle('selected',changed&&nextValue==='');row.querySelector('em').textContent=changed?(nextValue===''?'已清空':'已修改'):'保留';updateControls();});
  $$('#sanitizeComparisonList [data-clear-metadata]').forEach(button=>button.onclick=()=>{metadata.find(item=>item.field===button.dataset.clearMetadata).value='';renderSanitizationDetail();});
  $$('#sanitizeComparisonList [data-restore-metadata]').forEach(button=>button.onclick=()=>{const item=metadata.find(value=>value.field===button.dataset.restoreMetadata);item.value=item.originalValue;renderSanitizationDetail();});
  $$('#sanitizeComparisonList [data-restore-filesystem]').forEach(button=>button.onclick=()=>{const item=filesystem.find(value=>value.field===button.dataset.restoreFilesystem);item.value=item.originalValue;renderSanitizationDetail();});
  $$('#sanitizeComparisonList [data-set-removal]').forEach(button=>button.onclick=()=>{file.items.find(value=>value.id===button.dataset.setRemoval).selected=button.dataset.remove==='true';renderSanitizationDetail();});
  $$('#sanitizeComparisonList [data-metadata-all]').forEach(button=>button.onclick=()=>{metadata.forEach(item=>item.value=button.dataset.metadataAll==='clear'?'':item.originalValue);renderSanitizationDetail();});
  $$('#sanitizeComparisonList [data-filesystem-all]').forEach(button=>button.onclick=()=>{filesystem.forEach(item=>item.value=item.originalValue);renderSanitizationDetail();});
  $$('#sanitizeComparisonList [data-removal-all]').forEach(button=>button.onclick=()=>{const type=button.closest('[data-sanitize-group]').dataset.sanitizeGroup;file.items.filter(item=>item.type===type).forEach(item=>item.selected=button.dataset.removalAll==='delete');renderSanitizationDetail();});
  updateControls();
}
function renderWatermarkResult(result,action){const saved=action==='save',changes=(result.removed||0)+(result.modified||0)+(result.fileTimesModified||0);$('#watermarkSummary').textContent=result.status==='cleaned'?`${result.name} · 已${saved?'保存':'另存为'} · 共 ${changes} 项变化`:`${result.name||'当前文件'} · ${result.status==='unchanged'?'没有变化':'处理失败'}`;$('#watermarkResults').hidden=false;$('#watermarkResults').innerHTML=`<article class="watermark-result ${esc(result.status)}"><div><strong>${esc(result.name||result.sourcePath?.split(/[\\/]/).pop()||'当前文件')}</strong><small>${esc(result.destination||result.sourcePath||'')}</small><p>${result.status==='cleaned'?`已处理 ${changes} 项（删除内容 ${result.removed||0} 项，修改或清空文档属性 ${result.modified||0} 项，修改文件日期 ${result.fileTimesModified||0} 项），${saved?'原文件已更新':'已生成新文件'}`:result.status==='unchanged'?'脱敏前后没有变化':`处理失败：${esc(result.error||'不支持的文件')}`}</p>${result.destination?`<button data-output="${esc(result.destination)}">在文件夹中显示</button>`:''}</div><span class="result-status">${result.status==='cleaned'?'已完成':result.status==='unchanged'?'无变化':'需检查'}</span></article>`;const button=$('#watermarkResults [data-output]');if(button)button.onclick=()=>window.api.showFile(button.dataset.output);}
function sanitizationRequest(file,action){return {sourcePath:file.sourcePath,selectedIds:file.items.filter(item=>!['metadata','filesystem'].includes(item.type)&&item.selected).map(item=>item.id),metadataUpdates:Object.fromEntries(file.items.filter(item=>item.type==='metadata'&&String(item.value)!==String(item.originalValue)).map(item=>[item.field,item.value])),fileTimeUpdates:Object.fromEntries(file.items.filter(item=>item.type==='filesystem'&&String(item.value)!==String(item.originalValue)).map(item=>[item.field,item.value])),action};}
function requestHasChanges(request){return request.selectedIds.length||Object.keys(request.metadataUpdates).length||Object.keys(request.fileTimeUpdates).length;}
async function sanitizeCurrent(action){const current=sanitizationFiles[activeSanitizationIndex];if(!current)return;const chosen=batchTargets(),targets=chosen.length?chosen:[current],requests=targets.map(file=>sanitizationRequest(file,action)).filter(requestHasChanges);if(!requests.length)return;$('#sanitizeSave').disabled=true;$('#sanitizeSaveAs').disabled=true;setStatus(action==='save'?`正在保存 ${requests.length} 个文件`:`正在另存 ${requests.length} 个文件`);try{if(requests.length>1){const result=await window.api.sanitizeBatch({requests,action});if(!result){setStatus('已取消另存为');renderSanitizationWorkspace();return;}$('#watermarkResults').hidden=false;$('#watermarkResults').innerHTML=`<article class="watermark-result cleaned"><div><strong>${action==='save'?'批量保存完成':'批量脱敏包已生成'}</strong><small>${esc(result.destination||'')}</small><p>已处理 ${result.results.length} 个文件，共 ${result.results.reduce((sum,item)=>sum+(item.removed||0)+(item.modified||0),0)} 项变化。</p>${result.destination?`<button data-output="${esc(result.destination)}">在文件夹中显示</button>`:''}</div><span class="result-status">已完成</span></article>`;const output=$('#watermarkResults [data-output]');if(output)output.onclick=()=>window.api.showFile(output.dataset.output);if(action==='save'){const refreshed=await window.api.inspectSanitization(requests.map(item=>item.sourcePath));for(const item of refreshed){const index=sanitizationFiles.findIndex(file=>file.sourcePath===item.sourcePath);if(index>=0)sanitizationFiles[index]={...item,batchSelected:true};}}renderSanitizationWorkspace();setStatus(`批量脱敏完成 · ${result.results.length} 个文件`);return;}const file=targets[0],result=await window.api.sanitizeFile(requests[0]);if(!result){setStatus('已取消另存为');renderSanitizationDetail();return;}renderWatermarkResult({...result,name:file.name},action);if(action==='save'&&result.status==='cleaned'){const [updated]=await window.api.inspectSanitization([file.sourcePath]);sanitizationFiles[activeSanitizationIndex]={...updated,batchSelected:file.batchSelected};renderSanitizationWorkspace();}else renderSanitizationDetail();setStatus(result.status==='cleaned'?'脱敏处理完成':'当前文件没有变化');}catch(error){renderWatermarkResult({name:current.name,sourcePath:current.sourcePath,status:'error',error:error.message},action);renderSanitizationDetail();setStatus('脱敏处理失败');}}
$('#sanitizeSave').onclick=()=>sanitizeCurrent('save');
$('#sanitizeSaveAs').onclick=()=>sanitizeCurrent('saveAs');
$('#addSanitizeFiles').onclick=addSanitizationFiles;

function audit(){return project?.audit||{supplierStats:(project?.submissions||[]).map(item=>({id:item.id,supplier:item.supplier,zipName:item.zipName,fileCount:item.fileCount,totalSize:item.totalSize,totalSizeLabel:fmt(item.totalSize),parseErrors:item.files.filter(file=>file.parseError).length,types:Object.fromEntries([...new Set(item.files.map(file=>file.kind))].map(kind=>[kind,item.files.filter(file=>file.kind===kind).length]))})),identicalPackages:[],exactFiles:[],attributeMatches:[],similarityMatches:[],summary:{supplierCount:project?.submissions?.length||0,fileCount:allFiles().length,totalSizeLabel:fmt((project?.submissions||[]).reduce((sum,item)=>sum+item.totalSize,0)),identicalPackageGroups:0,exactFileGroups:0,attributeMatchGroups:0,similarityMatchGroups:0}};}
function kpi(label,value){return `<div class="kpi"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;}
function typeChips(types={}){return Object.entries(types).map(([kind,count])=>`<span class="type-chip">${typeName(kind)} ${count}</span>`).join('');}
function fileButton(file,className='mini-file'){const key=file.key||`${file.submissionId||''}|${file.supplier}|${file.path||file.zipPath}`;return `<button class="${className}" data-file-key="${esc(key)}"><span class="file-kind">${typeName(file.kind)}</span><span title="${esc(file.path||file.zipPath)}">${esc(file.path||file.zipPath||file.name)}</span><small>${fmt(file.size)}</small></button>`;}
function bindFileButtons(root=document){root.querySelectorAll('[data-file-key]').forEach(button=>button.onclick=()=>openCompareFile(button.dataset.fileKey));}
function auditFileSet(groups=[]){return new Set(groups.flatMap(group=>group.files||[]).map(ref=>`${ref.supplier}|${ref.path}`));}
function keyMetadata(file){const a=file.attributes||{},office=[['作者',a.author],['最后一次保存者',a.lastEditor],['修订号',a.revision],['版本号',a.version||a.appVersion],['程序名称',a.application],['公司',a.company],['管理者',a.manager],['创建内容的时间',a.created],['最后一次保存的日期',a.modified]],pdf=[['作者',a.author],['标题',a.title],['主题',a.subject],['关键词',a.keywords],['创建程序',a.creator],['制作工具',a.producer],['创建时间',a.created],['修改时间',a.modified]],image=[['作者',a.author],['标题',a.title],['说明',a.description],['创建软件',a.software]];return ['word','excel','powerpoint'].includes(file.kind)?office:file.kind==='pdf'?pdf:file.kind==='image'?image:[['作者',a.author],['创建时间',a.created],['修改时间',a.modified]];}
function pathMarkup(value){const normalized=String(value||'').replace(/\\/g,'/'),index=normalized.lastIndexOf('/'),directory=index>=0?normalized.slice(0,index+1):'',name=index>=0?normalized.slice(index+1):normalized;return `<span class="path-directory">${esc(directory)}</span><span class="path-basename">${esc(name)}</span>`;}
function refMatchesFile(ref,file){return ref.supplier===file.supplier&&ref.path===file.zipPath;}
function fileIssues(file,data){const issues=[];for(const group of data.exactFiles||[]){if(!group.files.some(ref=>refMatchesFile(ref,file)))continue;const peers=group.files.filter(ref=>!refMatchesFile(ref,file)).map(ref=>`${ref.supplier} / ${ref.path}`);issues.push({label:'相同文件',level:'high',title:`与 ${peers.join('；')} 的文件内容完全相同（SHA-256：${group.sha256}）`});}for(const group of data.attributeMatches||[]){if(!group.files.some(ref=>refMatchesFile(ref,file)))continue;const peers=group.files.filter(ref=>!refMatchesFile(ref,file)).map(ref=>`${ref.supplier} / ${ref.path}`);issues.push({label:`${group.label}重复`,level:group.riskLevel==='高风险'?'high':group.riskLevel==='中风险'?'medium':'low',title:`与 ${peers.join('；')} 的${group.label}相同：${group.value}`});}for(const group of data.similarityMatches||[]){if(!group.files.some(ref=>refMatchesFile(ref,file)))continue;const peers=group.files.filter(ref=>!refMatchesFile(ref,file)).map(ref=>`${ref.supplier} / ${ref.path}`);issues.push({label:group.kind==='media'?'媒体指纹相同':'文本相似',level:group.kind==='media'?'high':'medium',title:`与 ${peers.join('；')} 存在${group.label}：${group.value}`});}return issues;}
function issueTags(issues){return issues.length?`<span class="file-issue-tags">${issues.map(issue=>`<span class="issue-tag ${issue.level}" title="${esc(issue.title)}">${esc(issue.label)}</span>`).join('')}</span>`:'';}
function supplierFileCard(file,index,data){const metadata=keyMetadata(file),issues=fileIssues(file,data);return `<details class="supplier-file-card" ${index===0?'open':''}><summary><span class="file-sequence">${index+1}</span><span class="supplier-file-path">${pathMarkup(file.zipPath)}${issueTags(issues)}</span><span class="supplier-file-size">${fmt(file.size)}</span></summary><div class="supplier-file-body"><div class="key-metadata">${metadata.map(([label,value])=>{const empty=value==null||value===''||value==='未提取到';return `<div><span>${esc(label)}</span><strong class="${empty?'is-empty':''}">${empty?'&lt;空&gt;':esc(value)}</strong></div>`;}).join('')}</div><button class="view-file-detail" data-file-key="${esc(file.key)}">查看更多与编辑</button></div></details>`;}
function supplierColumn(stat,sets,data){const submission=project.submissions.find(item=>item.id===stat.id);let files=(submission?.files||[]).map(file=>({...file,supplier:submission.supplier,submissionId:submission.id,key:`${submission.id}|${submission.supplier}|${file.zipPath}`}));if(supplierFilters.exact)files=files.filter(file=>sets.exact.has(`${file.supplier}|${file.zipPath}`));if(supplierFilters.attribute)files=files.filter(file=>sets.attribute.has(`${file.supplier}|${file.zipPath}`));return `<article class="supplier-column"><header class="supplier-head"><strong title="${esc(stat.zipName)}">${esc(stat.supplier)}</strong><small>${esc(stat.zipName)}</small></header><div class="supplier-metrics"><div><span>文件</span><strong>${files.length}${files.length!==stat.fileCount?` / ${stat.fileCount}`:''}</strong></div><div><span>文件大小</span><strong>${esc(stat.totalSizeLabel||fmt(stat.totalSize))}</strong></div><div><span>解析异常</span><strong>${stat.parseErrors||0}</strong></div></div><div class="supplier-types">${typeChips(stat.types)}</div><div class="supplier-files">${files.length?files.map((file,index)=>supplierFileCard(file,index,data)).join(''):'<div class="supplier-empty">没有符合当前筛选的文件</div>'}</div></article>`;}
function setSupplierFilesOpen(root,open){root.querySelectorAll('.supplier-file-card').forEach(card=>card.open=open);}
function renderOverview(){const data=audit(),root=$('#compareOverview'),identical=data.identicalPackages||[],sets={exact:auditFileSet(data.exactFiles),attribute:auditFileSet(data.attributeMatches)};root.innerHTML=`<div class="kpi-grid">${kpi('供应商',data.summary.supplierCount)}${kpi('文件总数',data.summary.fileCount)}${kpi('文件总大小',data.summary.totalSizeLabel)}${kpi('完全相同文件组',data.summary.exactFileGroups)}${kpi('属性重复组',data.summary.attributeMatchGroups)}</div>${identical.length?`<div class="alert-banner fatal"><span>!</span><div><strong>致命：发现 ${identical.length} 组内容结构完全一致的供应商 ZIP</strong><span>${identical.map(group=>group.suppliers.join(' ↔ ')).join('；')}</span></div></div>`:''}<div class="section-heading review-heading"><div><h2>文件审查</h2><p>每列代表一家供应商；默认展开首个文件，路径、关键字段与重复问题直接可见。</p></div><div class="review-controls"><label><input id="filterExactFiles" type="checkbox" ${supplierFilters.exact?'checked':''}> 仅查看相同文件</label><label><input id="filterAttributeFiles" type="checkbox" ${supplierFilters.attribute?'checked':''}> 仅查看属性重复文件</label><span class="compact-actions"><button data-expand-suppliers class="icon-button" title="全部展开" aria-label="全部展开">+</button><button data-collapse-suppliers class="icon-button" title="全部收起" aria-label="全部收起">−</button></span></div></div><div class="supplier-board" style="--supplier-count:${Math.max(1,data.supplierStats.length)}">${data.supplierStats.map(stat=>supplierColumn(stat,sets,data)).join('')}</div>`;bindFileButtons(root);$('#filterExactFiles').onchange=event=>{supplierFilters.exact=event.target.checked;renderOverview();};$('#filterAttributeFiles').onchange=event=>{supplierFilters.attribute=event.target.checked;renderOverview();};root.querySelector('[data-expand-suppliers]').onclick=()=>setSupplierFilesOpen(root,true);root.querySelector('[data-collapse-suppliers]').onclick=()=>setSupplierFilesOpen(root,false);}
function refsForGroup(group){return group.files.map(ref=>{const file=allFiles().find(item=>item.submissionId===String(ref.key||'').split('|')[0]&&item.zipPath===ref.path)||allFiles().find(item=>item.supplier===ref.supplier&&item.zipPath===ref.path);return file?fileButton(file,'match-file'):`<div class="match-file"><span class="supplier-tag">${esc(ref.supplier)}</span><span>${esc(ref.path)}</span><small>${fmt(ref.size)}</small></div>`;}).join('');}
function duplicateFileRow(group,ref){const file=allFiles().find(item=>item.supplier===ref.supplier&&item.zipPath===ref.path),key=file?.key||ref.key,detail=`${group.label}：${group.value}`;return `<button class="duplicate-file-row" data-file-key="${esc(key)}"><span class="duplicate-file-name"><span class="supplier-tag">${esc(ref.supplier)}</span>${pathMarkup(ref.path)}</span><span class="duplicate-evidence"><strong>${esc(detail)}</strong><small>${esc(group.riskLevel||'低风险')}</small></span></button>`;}
function renderAttributeReview(){const data=audit(),root=$('#compareAttributes'),cards=groups=>groups.map(group=>`<article class="match-card duplicate-card"><div class="match-head"><strong>${group.kind==='simhash'?'文本':group.kind==='media'?'媒体':typeName(group.kind)} · ${esc(group.label)}：${esc(group.value)}</strong><span class="risk-chip risk-${group.riskLevel==='高风险'?'high':group.riskLevel==='中风险'?'medium':'low'}">${esc(group.riskLevel||'低风险')} · ${group.suppliers.length} 家供应商</span></div><div class="duplicate-files">${group.files.map(ref=>duplicateFileRow(group,ref)).join('')}</div></article>`).join('');root.innerHTML=`<div class="notice">所有非空重复属性都会列出；完全相同文件、SimHash 与媒体指纹由系统自动审查，无需手动选择。</div><div class="section-heading"><div><h2>跨供应商属性重复</h2><p>按“字段 + 标准化值”分组；完整路径与重复数据并排展示。</p></div><span>${data.attributeMatches.length} 组</span></div><div class="match-list duplicate-list">${data.attributeMatches.length?cards(data.attributeMatches):'<div class="empty-state"><div><strong>没有发现跨供应商属性重复</strong></div></div>'}</div><div class="section-heading"><div><h2>文本与媒体相似性线索</h2><p>展示文本 SimHash 与 Office 内嵌图片、媒体指纹证据。</p></div><span>${data.similarityMatches.length} 组</span></div><div class="match-list duplicate-list">${data.similarityMatches.length?cards(data.similarityMatches):'<div class="empty-state"><div><strong>没有发现文本或媒体相似性线索</strong></div></div>'}</div>`;bindFileButtons(root);}
function renderOperationReport(){const root=$('#compareReport'),logs=project.operationLog||[];root.innerHTML=`<div class="section-heading"><div><h2>操作记录</h2><p>记录属性修改、删除、保存和另存为结果，可随项目与报告导出。</p></div><span>${logs.length} 条</span></div>${logs.length?`<table class="report-table"><thead><tr><th>时间</th><th>供应商</th><th>文件</th><th>操作</th><th>修改内容</th><th>结果</th></tr></thead><tbody>${logs.map(log=>`<tr><td>${esc(new Date(log.at||log.createdAt).toLocaleString())}</td><td>${esc(log.supplier||'本地文件')}</td><td>${esc(log.file||log.zipPath)}</td><td>${esc(log.action==='save'?'保存':'另存为')}</td><td>${esc([...(log.changedFields||[]),...(log.deletedFields||[]).map(field=>`删除 ${field}`)].join('、')||'—')}</td><td>${esc(log.destination||'')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state"><div><strong>尚无文件操作</strong><p>在右侧属性编辑器保存修改后，操作会记录在这里。</p></div></div>'}`;}
function renderActiveSection(){for(const name of ['overview','attributes','report'])$('#compare'+name[0].toUpperCase()+name.slice(1)).hidden=name!==activeSection;$$('.workspace-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.section===activeSection));if(activeSection==='overview')renderOverview();if(activeSection==='attributes')renderAttributeReview();if(activeSection==='report')renderOperationReport();}
function renderCompare(){const data=audit();$('#compareProjectName').textContent=project.name;$('#compareSummary').textContent=`${data.summary.supplierCount} 家供应商 · ${data.summary.fileCount} 个文件 · ${data.summary.exactFileGroups} 组相同文件 · ${data.summary.attributeMatchGroups} 组属性重复 · ${data.summary.similarityMatchGroups||0} 组相似性线索`;renderActiveSection();}
$$('.workspace-tab').forEach(tab=>tab.onclick=()=>{activeSection=tab.dataset.section;renderActiveSection();});
function openCompareFile(key){const file=findFile(key);if(!file)return;selectedFileKey=key;$('#propertyDrawer').hidden=false;$('#drawerContext').textContent=`${file.supplier} / ${file.name}`;renderFileDetail(file,$('#drawerDetail'));}
$('#closeDrawer').onclick=()=>$('#propertyDrawer').hidden=true;

function renderEditor(){const files=allFiles(),query=($('#fileSearch').value||'').toLowerCase(),filtered=files.filter(file=>(file.name+' '+file.zipPath).toLowerCase().includes(query));$('#editorSummary').textContent=`${files.length} 个本地文件 · 直接查看、修改或清理支持的文档属性`;$('#editorFileCount').textContent=`${filtered.length} 个`;$('#editorFileList').innerHTML=filtered.map(file=>`<button class="file-row ${selectedFileKey===file.key?'selected':''}" data-editor-file="${esc(file.key)}"><span class="file-type-icon">${extensionLabel(file.name)}</span><span><strong>${esc(file.name)}</strong><small class="file-row-path">${esc(file.sourcePath||file.zipPath)}</small><small>${fmt(file.size)}</small></span></button>`).join('');$$('[data-editor-file]').forEach(button=>{button.onclick=()=>{selectedFileKey=button.dataset.editorFile;renderEditor();const file=findFile(selectedFileKey);$('#editorDetail').className='editor-detail';renderFileDetail(file,$('#editorDetail'));};button.oncontextmenu=event=>{event.preventDefault();const file=findFile(button.dataset.editorFile);showDocumentFileMenu(file?.sourcePath,()=>{const submission=project?.submissions?.find(item=>item.id===file.submissionId);if(submission)submission.files=submission.files.filter(item=>item!==file&&item.sourcePath!==file.sourcePath);if(selectedFileKey===file.key)selectedFileKey='';renderEditor();});};});if(selectedFileKey){const file=findFile(selectedFileKey);if(file&&!$('#editorDetail .file-detail-sticky'))renderFileDetail(file,$('#editorDetail'));}}
async function addEditorFiles(){const selected=await window.api.pickFiles();if(!selected.length)return;inputFiles=[...new Set([...inputFiles,...selected])];showView('working');project=await window.api.analyze(inputFiles,{mode:'files'});selectedFileKey='';renderEditor();showView('editorWorkspace');}
$('#fileSearch').oninput=renderEditor;$('#addEditorFilesInline').onclick=addEditorFiles;
function setExplorerWidth(value){const layout=$('.editor-layout'),max=Math.max(280,layout.getBoundingClientRect().width*.55);layout.style.setProperty('--explorer-width',`${Math.min(max,Math.max(220,value))}px`);}
$('#editorSplitter').onpointerdown=event=>{const splitter=event.currentTarget,startX=event.clientX,startWidth=$('.explorer').getBoundingClientRect().width;splitter.setPointerCapture(event.pointerId);splitter.classList.add('dragging');splitter.onpointermove=move=>setExplorerWidth(startWidth+move.clientX-startX);splitter.onpointerup=()=>{splitter.classList.remove('dragging');splitter.onpointermove=null;splitter.onpointerup=null;};};
$('#editorSplitter').onkeydown=event=>{if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();setExplorerWidth($('.explorer').getBoundingClientRect().width+(event.key==='ArrowRight'?20:-20));};

function displayValue(value){if(Array.isArray(value))return value.map(item=>typeof item==='object'?esc(JSON.stringify(item)):esc(item)).join('<br>');if(value&&typeof value==='object')return `<pre>${esc(JSON.stringify(value,null,2))}</pre>`;if(typeof value==='boolean')return value?'是':'否';return esc(value);}
function renderFileDetail(file,root){
  if(!file)return;const q=selector=>root.querySelector(selector),qa=selector=>[...root.querySelectorAll(selector)],groups=file.propertyGroups||[],canEdit=['word','excel','powerpoint','pdf'].includes(file.kind),office=file.kind!=='pdf',stateKey=`${file.sourcePath||file.containerPath||file.supplier}|${file.zipPath}`,unlinked=metadataLinkState.get(stateKey)||new Set();
  const labels={作者:'author','最后一次保存者':'lastEditor',修订号:'revision',版本号:'appVersion',程序名称:'application',公司:'company',管理者:'manager','创建内容的时间':'created','最后一次保存的日期':'modified',标题:'title',主题:'subject',关键词:'keywords',说明:'description',模板:'template','创建程序':'creator','制作工具':'producer','创建时间':'created','修改时间':'modified','自定义属性哈希':'customProperties'};
  const pdfFields=new Set(['author','title','subject','keywords','created','modified','creator','producer']),officeFields=new Set(['author','lastEditor','revision','appVersion','application','company','manager','created','modified','lastPrinted','title','subject','keywords','description','template','customProperties']),supported=field=>canEdit&&(office?officeFields:pdfFields).has(field),editable=field=>field!=='customProperties';
  const normalRow=(name,value)=>{const field=labels[name];if(!field||!supported(field))return `<dt>${esc(name)}</dt><dd>${displayValue(value)}</dd>`;const current=file.attributes?.[field]??(field==='appVersion'?file.attributes?.version:''),shown=current==null||current==='未提取到'?'':current;return `<dt>${esc(name)}</dt><dd class="property-editor"><label class="delete-property" title="选择此属性"><input type="checkbox" data-field="${field}" data-source="info"></label>${editable(field)?`<input class="property-value" data-field="${field}" data-source="info" data-original="${esc(shown)}" value="${esc(shown)}" aria-label="修改${esc(name)}">`:`<span>${displayValue(value)}</span>`}</dd>`;};
  const metadataCell=(name,item,source)=>{if(source==='info'&&item.infoReadOnly)return '<div class="metadata-cell metadata-na">不适用</div>';const shown=item[source]==='未提取到'?'':item[source],readonly=source==='xmp'&&!unlinked.has(item.field)?'readonly':'';return `<div class="metadata-cell"><label class="delete-property" title="选择此属性"><input type="checkbox" data-field="${item.field}" data-source="${source}"></label><input class="property-value" data-field="${item.field}" data-source="${source}" data-original="${esc(shown)}" value="${esc(shown)}" ${readonly} aria-label="修改 ${esc(name)} ${source==='info'?'Info':'XMP'} 值"></div>`;};
  const metadataRow=(name,item)=>{const linked=!unlinked.has(item.field);return `<div class="metadata-row"><div class="metadata-name">${esc(name)}</div>${metadataCell(name,item,'info')}<button class="field-link ${linked?'linked':'unlinked'}" data-field="${item.field}" title="${linked?'点击解除 Info 与 XMP 联动':'已解除，点击恢复联动'}">${linked?'🔗':'⛓'}</button>${metadataCell(name,item,'xmp')}</div>`;};
  const toolbar=canEdit?`<section class="edit-toolbar"><div class="bulk-actions"><label class="toolbar-check"><input type="checkbox" data-select-all> 全选</label></div><div class="save-summary"><span data-split-warning hidden>部分 Info 与 XMP 已解除关联，不同阅读器可能显示不同值。</span><span data-save-status role="status">${file.sourcePath?'保存会覆盖当前文件。':'ZIP 内文件只能另存为。'}</span></div><div class="edit-buttons"><small data-selected-count>已选择 0 项</small><label class="toolbar-check delete-mark"><input type="checkbox" data-mark-delete disabled> 删除所选属性</label><button data-save ${file.sourcePath?'':'disabled'}>保存</button><button data-save-as class="primary">另存为</button></div></section>`:'';
  const groupHtml=group=>group.id==='pdf-metadata'?`<details class="property-section" open><summary><span>${esc(group.title)}</span><small>${Object.keys(group.items).length} 项 · XMP ${esc(group.xmpStatus)}</small></summary><div class="metadata-table"><div class="metadata-row metadata-head"><div>属性</div><div>传统 PDF Info Dictionary</div><div></div><div>XMP Metadata Stream</div></div>${Object.entries(group.items).map(([name,item])=>metadataRow(name,item)).join('')}</div></details>`:`<details class="property-section" open><summary><span>${esc(group.title)}</span><small>${Object.keys(group.items).length} 项</small></summary><dl>${Object.entries(group.items).map(([name,value])=>normalRow(name,value)).join('')}</dl></details>`;
  root.innerHTML=`<div class="file-detail-sticky"><div class="file-title-line"><div class="file-name-row" title="${esc(file.name)}">${esc(file.name)}</div><div class="detail-section-actions"><button class="icon-button" data-expand-sections title="全部展开" aria-label="全部展开">+</button><button class="icon-button" data-collapse-sections title="全部收起" aria-label="全部收起">−</button></div></div><div class="file-info-row"><span>${esc(file.supplier)}</span><span>${typeName(file.kind)}</span><span class="path-muted" title="${esc(file.zipPath)}">${esc(file.zipPath)}</span><span data-file-size>${fmt(file.size)}</span></div>${toolbar}</div><div>${groups.map(groupHtml).join('')}</div>`;
  q('[data-expand-sections]').onclick=()=>qa('.property-section').forEach(section=>section.open=true);q('[data-collapse-sections]').onclick=()=>qa('.property-section').forEach(section=>section.open=false);
  if(!canEdit)return;
  let lastEditable=null;const twin=(selector,node)=>q(`${selector}[data-field="${node.dataset.field}"][data-source="${node.dataset.source==='xmp'?'info':'xmp'}"]`),isLinked=field=>!!q(`.field-link[data-field="${field}"].linked`),updateInput=input=>{const box=q(`.delete-property input[data-field="${input.dataset.field}"][data-source="${input.dataset.source}"]`);input.disabled=false;input.readOnly=(input.dataset.source==='xmp'&&isLinked(input.dataset.field))||box?.dataset.armed==='true';},showStatus=(message,state='')=>{const status=q('[data-save-status]');status.textContent=message;status.dataset.state=state;};
  const updateSelection=()=>{const boxes=qa('.delete-property input'),selected=boxes.filter(box=>box.checked),count=new Set(selected.map(box=>box.dataset.field)).size,all=q('[data-select-all]'),mark=q('[data-mark-delete]');q('[data-selected-count]').textContent=`已选择 ${count} 项`;all.checked=boxes.length>0&&selected.length===boxes.length;all.indeterminate=selected.length>0&&selected.length<boxes.length;mark.disabled=count===0;if(!count){mark.checked=false;boxes.forEach(box=>delete box.dataset.armed);}};
  qa('.delete-property input').forEach(box=>box.onchange=()=>{if(isLinked(box.dataset.field)){const other=twin('.delete-property input',box);if(other)other.checked=box.checked;}qa('.delete-property input').forEach(item=>delete item.dataset.armed);q('[data-mark-delete]').checked=false;updateSelection();qa('.property-value').forEach(updateInput);});
  qa('.property-value').forEach(input=>{input.onfocus=()=>{if(!input.readOnly)lastEditable=input;};input.oninput=()=>{if(isLinked(input.dataset.field)){const other=twin('.property-value',input);if(other)other.value=input.value;}};});
  qa('.field-link').forEach(button=>button.onclick=()=>{button.classList.toggle('linked');button.classList.toggle('unlinked');button.textContent=button.classList.contains('linked')?'🔗':'⛓';if(button.classList.contains('linked'))unlinked.delete(button.dataset.field);else unlinked.add(button.dataset.field);metadataLinkState.set(stateKey,unlinked);const xmp=q(`.property-value[data-field="${button.dataset.field}"][data-source="xmp"]`),info=q(`.property-value[data-field="${button.dataset.field}"][data-source="info"]`);if(button.classList.contains('linked')&&info&&xmp)xmp.value=info.value;if(xmp)updateInput(xmp);q('[data-split-warning]').hidden=!qa('.field-link.unlinked').length;});
  q('[data-select-all]').onchange=event=>{qa('.delete-property input').forEach(box=>{box.checked=event.target.checked;delete box.dataset.armed;});q('[data-mark-delete]').checked=false;qa('.property-value').forEach(updateInput);updateSelection();};
  q('[data-mark-delete]').onchange=event=>{qa('.delete-property input:checked').forEach(box=>{if(event.target.checked)box.dataset.armed='true';else delete box.dataset.armed;});qa('.property-value').forEach(updateInput);q('[data-selected-count]').textContent=`已选择 ${new Set(qa('.delete-property input:checked').map(box=>box.dataset.field)).size} 项${event.target.checked?'，保存时删除':''}`;};
  const submit=async action=>{const syncMetadata=file.kind!=='pdf'||qa('.field-link').every(link=>link.classList.contains('linked')),fields=qa('.delete-property input:checked').filter(box=>box.dataset.armed==='true'&&box.dataset.source!=='xmp').map(box=>box.dataset.field),xmpFields=qa('.delete-property input:checked').filter(box=>box.dataset.armed==='true'&&box.dataset.source==='xmp').map(box=>box.dataset.field),updates={},xmpUpdates={};qa('.property-value').forEach(input=>{const deleted=(input.dataset.source==='xmp'?xmpFields:fields).includes(input.dataset.field);if(!deleted&&input.value!==String(input.dataset.original??''))(input.dataset.source==='xmp'?xmpUpdates:updates)[input.dataset.field]=input.value;});if(!fields.length&&!xmpFields.length&&!Object.keys(updates).length&&!Object.keys(xmpUpdates).length){showStatus(qa('.delete-property input:checked').length?'请先勾选“删除所选属性”，再保存。':'没有需要保存的属性更改','warning');return;}const save=q('[data-save]'),saveAs=q('[data-save-as]');save.disabled=true;saveAs.disabled=true;showStatus(action==='save'?'正在写入并验证属性…':'正在生成并验证副本…','working');try{const result=await window.api.clean({sourcePath:file.sourcePath,zipPath:file.containerPath,entryPath:file.zipPath,kind:file.kind,fields,updates,xmpFields,xmpUpdates,syncMetadata,action,supplier:file.supplier,submissionId:file.submissionId});if(!result){showStatus('操作已取消');return;}if(action==='save'){updateProjectFile(file,result.verifiedFile);qa('.property-value').forEach(input=>{const attrs=result.verifiedFile.attributes||{},next=input.dataset.source==='xmp'?(attrs.xmp?.[input.dataset.field]??''):(attrs[input.dataset.field]??(input.dataset.field==='appVersion'?attrs.version:'')??'');input.value=String(next==='未提取到'?'':next);input.dataset.original=input.value;});qa('.delete-property input').forEach(box=>{box.checked=false;delete box.dataset.armed;});qa('.property-value').forEach(updateInput);updateSelection();q('[data-file-size]').textContent=fmt(file.size);showStatus('已保存并验证，可以继续编辑。','success');const resume=lastEditable?.isConnected&&!lastEditable.readOnly?lastEditable:qa('.property-value').find(input=>!input.readOnly);if(resume)requestAnimationFrame(()=>{resume.focus({preventScroll:true});resume.setSelectionRange(resume.value.length,resume.value.length);});}else showStatus(`已另存为并验证：${result.destination}`,'success');const operation=result.operation||{at:new Date().toISOString(),supplier:file.supplier,file:file.zipPath,action,destination:result.destination,changedFields:[...Object.keys(updates),...Object.keys(xmpUpdates).map(field=>`XMP ${field}`)],deletedFields:[...fields,...xmpFields.map(field=>`XMP ${field}`)]};project.operationLog=project.operationLog||[];if(!project.operationLog.some(item=>item.id&&item.id===operation.id))project.operationLog.push(operation);if(activeSection==='report')renderOperationReport();}catch(error){showStatus('保存失败：'+error.message,'error');}finally{save.disabled=!file.sourcePath;saveAs.disabled=false;}};
  q('[data-save]').onclick=()=>submit('save');q('[data-save-as]').onclick=()=>submit('saveAs');qa('.property-value').forEach(updateInput);q('[data-split-warning]').hidden=!qa('.field-link.unlinked').length;updateSelection();
}

$$('.backHome').forEach(button=>button.onclick=()=>showView('start'));$('#newWorkspace').onclick=()=>{project=null;inputFiles=[];selectedFileKey='';metadataLinkState.clear();showView('start');renderChosen();};
$('#saveProject').onclick=$('#saveEditorProject').onclick=()=>window.api.save();$('#exportPdf').onclick=()=>window.api.export('pdf');$('#exportXlsx').onclick=()=>window.api.export('xlsx');
$('#openProject').onclick=async()=>{const opened=await window.api.open();if(!opened)return;project=opened;project.operationLog=project.operationLog||[];metadataLinkState.clear();selectedFileKey='';mode=project.mode==='files'?'files':'compare';setMode(mode,{clear:false});if(mode==='files'){renderEditor();showView('editorWorkspace');}else{activeSection='overview';renderCompare();showView('compareWorkspace');}};
setMode('compare');showView('start');
