'use strict';

let inputFiles=[],project=null,mode='compare',activeSection='overview',selectedFileKey='',metadataLinkState=new Map(),supplierFilters={exact:false,attribute:false},watermarkOutput='',sanitizationFiles=[],activeSanitizationIndex=0;
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const fmt=value=>{const n=Number(value)||0;if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(1)} GB`;};
const typeName=kind=>({pdf:'PDF',word:'Word',excel:'Excel',powerpoint:'PowerPoint',image:'图片',text:'文本',zip:'ZIP',mixed:'多类型'}[kind]||'其他');
const views=['start','working','compareWorkspace','editorWorkspace','watermarkWorkspace'];
function showView(id){for(const view of views)$('#'+view).hidden=view!==id;$('#propertyDrawer').hidden=true;$('#workspaceTitle').textContent=id==='start'?'开始':id==='working'?'正在处理':id==='compareWorkspace'?'供应商批量审查':id==='watermarkWorkspace'?'文件脱敏':'文件属性编辑器';}
function setStatus(message){$('#statusText').textContent=message;}
function fileKey(file){return `${file.submissionId||''}|${file.supplier||''}|${file.zipPath}`;}
function allFiles(){return (project?.submissions||[]).flatMap(submission=>submission.files.map(file=>({...file,supplier:file.supplier||submission.supplier,submissionId:submission.id,containerPath:submission.zipPath,zipName:submission.zipName,key:`${submission.id}|${submission.supplier}|${file.zipPath}`})));}
function findFile(key){return allFiles().find(file=>file.key===key);}
function updateProjectFile(file,verified){const submission=project?.submissions?.find(item=>item.id===file.submissionId);const target=submission?.files.find(item=>item.zipPath===file.zipPath);if(target){target.attributes=verified.attributes;target.propertyGroups=verified.propertyGroups;target.sha256=verified.sha256;target.size=verified.size;}Object.assign(file,{attributes:verified.attributes,propertyGroups:verified.propertyGroups,sha256:verified.sha256,size:verified.size});}

function setMode(next,{clear=true}={}){mode=next;if(clear)inputFiles=[];$$('.workspace-card').forEach(card=>card.classList.toggle('active',card.dataset.mode===mode));$$('.activity[data-home]').forEach(button=>button.classList.toggle('active',button.dataset.home===mode));const copy={compare:['添加供应商 ZIP','每个 ZIP 文件名将作为一家供应商名称','开始供应商审查'],files:['添加需要编辑的文件','支持 Office、PDF、图片和文本文件','打开文件属性编辑器'],watermark:['添加需要脱敏的文件','支持 Word、Excel 和 PDF','打开文件脱敏工作台']}[mode];$('#dropTitle').textContent=copy[0];$('#dropHint').textContent=copy[1];$('#run').textContent=copy[2];renderChosen();}
function inputTypeLabel(file){if(mode==='compare')return'ZIP';const extension=(file.match(/\.[^.]+$/)||[''])[0].toLowerCase();return ['.docx','.docm'].includes(extension)?'Word':['.xlsx','.xlsm'].includes(extension)?'Excel':extension==='.pdf'?'PDF':'文件';}
function renderChosen(){$('#chosen').innerHTML=inputFiles.map((file,index)=>`<div class="chosen-file"><span class="zip-icon">${inputTypeLabel(file)}</span><div><strong>${esc(file.split(/[\\/]/).pop().replace(mode==='compare'?/\.zip$/i:/$^/,''))}</strong><small>${esc(file)}</small></div><span class="ready">已就绪</span><button class="remove" data-index="${index}">移除</button></div>`).join('');$('#run').disabled=mode==='compare'?inputFiles.length<2:inputFiles.length<1;$$('.chosen-file .remove').forEach(button=>button.onclick=event=>{event.stopPropagation();inputFiles.splice(Number(button.dataset.index),1);renderChosen();});}
async function chooseFiles(){const selected=mode==='compare'?await window.api.pick():mode==='watermark'?await window.api.pickWatermarkFiles():await window.api.pickFiles();inputFiles=[...new Set([...inputFiles,...selected])];renderChosen();}
$$('.workspace-card').forEach(card=>card.onclick=()=>setMode(card.dataset.mode));$$('.activity[data-home]').forEach(button=>button.onclick=()=>{showView('start');setMode(button.dataset.home);});
$('#drop').onclick=chooseFiles;$('#drop').ondragover=event=>{event.preventDefault();$('#drop').classList.add('over');};$('#drop').ondragleave=()=>$('#drop').classList.remove('over');$('#drop').ondrop=event=>{event.preventDefault();$('#drop').classList.remove('over');const incoming=[...event.dataTransfer.files].filter(file=>mode==='files'||(mode==='compare'?/\.zip$/i:/\.(docx|docm|xlsx|xlsm|pdf)$/i).test(file.name)).map(file=>file.path);inputFiles=[...new Set([...inputFiles,...incoming])];renderChosen();};
window.api.progress(progress=>{const prefix=progress.suppliers?`供应商 ${progress.supplier}/${progress.suppliers} · `:'';$('#step').textContent=`${prefix}${progress.name}`;$('#bar').value=progress.total?progress.done/progress.total*100:0;setStatus(`正在处理 ${progress.name}`);});
$('#run').onclick=async()=>{showView('working');$('#workingTitle').textContent=mode==='watermark'?'正在检查可脱敏内容':'正在本地审查';setStatus('处理中');try{if(mode==='watermark'){sanitizationFiles=await window.api.inspectSanitization(inputFiles);activeSanitizationIndex=0;renderSanitizationWorkspace();showView('watermarkWorkspace');setStatus(`完成 · 已检查 ${sanitizationFiles.length} 个文件`);return;}project=await window.api.analyze(inputFiles,{mode});project.operationLog=project.operationLog||[];metadataLinkState.clear();selectedFileKey='';if(mode==='compare'){activeSection='overview';renderCompare();showView('compareWorkspace');}else{renderEditor();showView('editorWorkspace');}setStatus(`完成 · ${allFiles().length} 个文件`);}catch(error){alert('处理失败：'+error.message);showView('start');setStatus('处理失败');}};

function renderSanitizationWorkspace(){
  $('#sanitizeFileCount').textContent=`${sanitizationFiles.length} 个`;
  $('#sanitizeFileList').innerHTML=sanitizationFiles.map((file,index)=>`<button class="sanitize-file ${index===activeSanitizationIndex?'active':''}" data-sanitize-file="${index}"><strong>${esc(file.name)}</strong><small>${esc(file.sourcePath)}</small><span>${file.error?'解析失败':`${file.items.length} 项可脱敏${file.hasRevisions?' · 修订中':''}`}</span></button>`).join('');
  $$('#sanitizeFileList [data-sanitize-file]').forEach(button=>button.onclick=()=>{activeSanitizationIndex=Number(button.dataset.sanitizeFile);renderSanitizationWorkspace();});
  renderSanitizationDetail();
}
async function addSanitizationFiles(){const selected=await window.api.pickWatermarkFiles(),existing=new Set(sanitizationFiles.map(file=>file.sourcePath)),incoming=selected.filter(file=>!existing.has(file));if(!incoming.length)return;setStatus('正在检查新增文件');const inspected=await window.api.inspectSanitization(incoming);sanitizationFiles.push(...inspected);activeSanitizationIndex=sanitizationFiles.length-inspected.length;renderSanitizationWorkspace();setStatus(`已添加 ${inspected.length} 个文件`);}
function renderSanitizationDetail(){
  const file=sanitizationFiles[activeSanitizationIndex];if(!file)return;
  const byType=type=>file.items.filter(item=>item.type===type),watermarks=byType('watermark'),comments=byType('comment'),metadata=byType('metadata');
  $('#revisionWarning').innerHTML=file.hasRevisions?`<div class="revision-warning"><strong>当前处于修订模式，建议打开源文件 → 审阅 → 接受所有修订</strong><span>检测到 ${file.revisionCount||0} 个修订标记；PreSalesX 不会擅自接受或拒绝修订。</span></div>`:'';
  const group=(type,label,items)=>`<section class="sanitize-group"><header><label><input type="checkbox" data-sanitize-type="${type}" ${items.length?'':'disabled'}> ${label}</label><span>${items.length} 项</span></header>${items.length?items.map(item=>`<label class="sanitize-option"><input type="checkbox" data-sanitize-id="${esc(item.id)}" ${item.selected?'checked':''}><span><strong>${esc(item.label)}</strong><small>${esc(item.detail)}</small></span></label>`).join(''):'<p class="sanitize-none">未检测到此类内容</p>'}</section>`;
  $('#sanitizeOptionList').innerHTML=group('watermark','水印与背景',watermarks)+group('comment','批注',comments)+group('metadata','关键文件属性（勾选后清空）',metadata);
  const updateControls=()=>{const all=file.items,selected=all.filter(item=>item.selected);$('#sanitizeSelectAll').disabled=!all.length;$('#sanitizeSelectAll').checked=all.length>0&&selected.length===all.length;$('#sanitizeSelectAll').indeterminate=selected.length>0&&selected.length<all.length;for(const type of ['watermark','comment','metadata']){const items=all.filter(item=>item.type===type),box=$(`[data-sanitize-type="${type}"]`);if(!box)continue;box.disabled=!items.length;box.checked=items.length>0&&items.every(item=>item.selected);box.indeterminate=items.some(item=>item.selected)&&!box.checked;}$('#sanitizeSelected').disabled=!sanitizationFiles.some(value=>value.items.some(item=>item.selected));};
  $$('#sanitizeOptionList [data-sanitize-id]').forEach(box=>box.onchange=()=>{file.items.find(item=>item.id===box.dataset.sanitizeId).selected=box.checked;updateControls();});
  $$('#sanitizeOptionList [data-sanitize-type]').forEach(box=>box.onchange=()=>{file.items.filter(item=>item.type===box.dataset.sanitizeType).forEach(item=>item.selected=box.checked);renderSanitizationDetail();});
  $('#sanitizeSelectAll').onchange=event=>{file.items.forEach(item=>item.selected=event.target.checked);renderSanitizationDetail();};
  updateControls();
}
function renderWatermarkResults(result){$('#watermarkSummary').textContent=`${result.results.length} 个文件 · 成功生成 ${result.cleaned} 个脱敏副本 · 共移除 ${result.removed} 项内容`;$('#watermarkResults').hidden=false;$('#watermarkResults').innerHTML=result.results.map((item,index)=>`<article class="watermark-result ${esc(item.status)}"><span class="file-sequence">${index+1}</span><div><strong>${esc(item.sourcePath.split(/[\\/]/).pop())}</strong><small>${esc(item.sourcePath)}</small><p>${item.status==='cleaned'?`已移除 ${item.removed} 项并生成脱敏副本`:item.status==='unchanged'?'没有选中或未找到可移除内容':`处理失败：${esc(item.error||'不支持的文件')}`}</p>${item.destination?`<button data-output="${esc(item.destination)}">在文件夹中显示</button>`:''}</div><span class="result-status">${item.status==='cleaned'?'已完成':item.status==='unchanged'?'无变化':'需检查'}</span></article>`).join('');$$('#watermarkResults [data-output]').forEach(button=>button.onclick=()=>window.api.showFile(button.dataset.output));}
$('#sanitizeSelected').onclick=async()=>{const requests=sanitizationFiles.map(file=>({sourcePath:file.sourcePath,selectedIds:file.items.filter(item=>item.selected).map(item=>item.id)})).filter(item=>item.selectedIds.length);const result=await window.api.sanitizeFiles(requests);if(result)renderWatermarkResults(result);};
$('#addSanitizeFiles').onclick=addSanitizationFiles;

function audit(){return project?.audit||{supplierStats:(project?.submissions||[]).map(item=>({id:item.id,supplier:item.supplier,zipName:item.zipName,fileCount:item.fileCount,totalSize:item.totalSize,totalSizeLabel:fmt(item.totalSize),parseErrors:item.files.filter(file=>file.parseError).length,types:Object.fromEntries([...new Set(item.files.map(file=>file.kind))].map(kind=>[kind,item.files.filter(file=>file.kind===kind).length]))})),identicalPackages:[],exactFiles:[],attributeMatches:[],similarityMatches:[],summary:{supplierCount:project?.submissions?.length||0,fileCount:allFiles().length,totalSizeLabel:fmt((project?.submissions||[]).reduce((sum,item)=>sum+item.totalSize,0)),identicalPackageGroups:0,exactFileGroups:0,attributeMatchGroups:0,similarityMatchGroups:0}};}
function kpi(label,value){return `<div class="kpi"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;}
function typeChips(types={}){return Object.entries(types).map(([kind,count])=>`<span class="type-chip">${typeName(kind)} ${count}</span>`).join('');}
function fileButton(file,className='mini-file'){const key=file.key||`${file.submissionId||''}|${file.supplier}|${file.path||file.zipPath}`;return `<button class="${className}" data-file-key="${esc(key)}"><span class="file-kind">${typeName(file.kind)}</span><span title="${esc(file.path||file.zipPath)}">${esc(file.path||file.zipPath||file.name)}</span><small>${fmt(file.size)}</small></button>`;}
function bindFileButtons(root=document){root.querySelectorAll('[data-file-key]').forEach(button=>button.onclick=()=>openCompareFile(button.dataset.fileKey));}
function auditFileSet(groups=[]){return new Set(groups.flatMap(group=>group.files||[]).map(ref=>`${ref.supplier}|${ref.path}`));}
function keyMetadata(file){const a=file.attributes||{},office=[['作者',a.author],['最后一次保存者',a.lastEditor],['修订号',a.revision],['版本号',a.version||a.appVersion],['程序名称',a.application],['公司',a.company],['管理者',a.manager],['创建内容的时间',a.created],['最后一次保存的日期',a.modified]],pdf=[['作者',a.author],['标题',a.title],['主题',a.subject],['关键词',a.keywords],['创建程序',a.creator],['制作工具',a.producer],['创建时间',a.created],['修改时间',a.modified]],image=[['作者',a.author],['标题',a.title],['说明',a.description],['创建软件',a.software]];return ['word','excel','powerpoint'].includes(file.kind)?office:file.kind==='pdf'?pdf:file.kind==='image'?image:[['作者',a.author],['创建时间',a.created],['修改时间',a.modified]];}
function pathMarkup(value){const normalized=String(value||'').replace(/\\/g,'/'),index=normalized.lastIndexOf('/'),directory=index>=0?normalized.slice(0,index+1):'',name=index>=0?normalized.slice(index+1):normalized;return `<span class="path-directory">${esc(directory)}</span><span class="path-basename">${esc(name)}</span>`;}
function refMatchesFile(ref,file){return ref.supplier===file.supplier&&ref.path===file.zipPath;}
function fileIssues(file,data){const issues=[];for(const group of data.exactFiles||[]){if(!group.files.some(ref=>refMatchesFile(ref,file)))continue;const peers=group.files.filter(ref=>!refMatchesFile(ref,file)).map(ref=>`${ref.supplier} / ${ref.path}`);issues.push({label:'相同文件',level:'high',title:`与 ${peers.join('；')} 的文件内容完全相同（SHA-256：${group.sha256}）`});}for(const group of data.attributeMatches||[]){if(!group.files.some(ref=>refMatchesFile(ref,file)))continue;const peers=group.files.filter(ref=>!refMatchesFile(ref,file)).map(ref=>`${ref.supplier} / ${ref.path}`);issues.push({label:`${group.label}重复`,level:group.riskLevel==='高风险'?'high':group.riskLevel==='中风险'?'medium':'low',title:`与 ${peers.join('；')} 的${group.label}相同：${group.value}`});}for(const group of data.similarityMatches||[]){if(!group.files.some(ref=>refMatchesFile(ref,file)))continue;const peers=group.files.filter(ref=>!refMatchesFile(ref,file)).map(ref=>`${ref.supplier} / ${ref.path}`);issues.push({label:group.kind==='media'?'媒体指纹相同':'文本相似',level:group.kind==='media'?'high':'medium',title:`与 ${peers.join('；')} 存在${group.label}：${group.value}`});}return issues;}
function issueTags(issues){return issues.length?`<span class="file-issue-tags">${issues.map(issue=>`<span class="issue-tag ${issue.level}" title="${esc(issue.title)}">${esc(issue.label)}</span>`).join('')}</span>`:'';}
function supplierFileCard(file,index,data){const metadata=keyMetadata(file),issues=fileIssues(file,data);return `<details class="supplier-file-card" ${index===0?'open':''}><summary><span class="file-sequence">${index+1}</span><span class="supplier-file-path">${pathMarkup(file.zipPath)}${issueTags(issues)}</span><span class="supplier-file-size">${fmt(file.size)}</span></summary><div class="supplier-file-body"><div class="key-metadata">${metadata.map(([label,value])=>{const empty=value==null||value===''||value==='未提取到';return `<div><span>${esc(label)}</span><strong class="${empty?'is-empty':''}">${empty?'&lt;空&gt;':esc(value)}</strong></div>`;}).join('')}</div><button class="view-file-detail" data-file-key="${esc(file.key)}">查看更多与编辑</button></div></details>`;}
function supplierColumn(stat,sets,data){const submission=project.submissions.find(item=>item.id===stat.id);let files=(submission?.files||[]).map(file=>({...file,supplier:submission.supplier,submissionId:submission.id,key:`${submission.id}|${submission.supplier}|${file.zipPath}`}));if(supplierFilters.exact)files=files.filter(file=>sets.exact.has(`${file.supplier}|${file.zipPath}`));if(supplierFilters.attribute)files=files.filter(file=>sets.attribute.has(`${file.supplier}|${file.zipPath}`));return `<article class="supplier-column"><header class="supplier-head"><strong title="${esc(stat.zipName)}">${esc(stat.supplier)}</strong><small>${esc(stat.zipName)}</small></header><div class="supplier-metrics"><div><span>文件</span><strong>${files.length}${files.length!==stat.fileCount?` / ${stat.fileCount}`:''}</strong></div><div><span>文件大小</span><strong>${esc(stat.totalSizeLabel||fmt(stat.totalSize))}</strong></div><div><span>解析异常</span><strong>${stat.parseErrors||0}</strong></div></div><div class="supplier-types">${typeChips(stat.types)}</div><div class="supplier-files">${files.length?files.map((file,index)=>supplierFileCard(file,index,data)).join(''):'<div class="supplier-empty">没有符合当前筛选的文件</div>'}</div></article>`;}
function setSupplierFilesOpen(root,open){root.querySelectorAll('.supplier-file-card').forEach(card=>card.open=open);}
function renderOverview(){const data=audit(),root=$('#compareOverview'),identical=data.identicalPackages||[],sets={exact:auditFileSet(data.exactFiles),attribute:auditFileSet(data.attributeMatches)};root.innerHTML=`<div class="kpi-grid">${kpi('供应商',data.summary.supplierCount)}${kpi('文件总数',data.summary.fileCount)}${kpi('文件总大小',data.summary.totalSizeLabel)}${kpi('完全相同文件组',data.summary.exactFileGroups)}${kpi('属性重复组',data.summary.attributeMatchGroups)}</div>${identical.length?`<div class="alert-banner fatal"><span>!</span><div><strong>致命：发现 ${identical.length} 组内容结构完全一致的供应商 ZIP</strong><span>${identical.map(group=>group.suppliers.join(' ↔ ')).join('；')}</span></div></div>`:''}<div class="section-heading review-heading"><div><h2>文件审查</h2><p>每列代表一家供应商；默认展开首个文件，路径、关键字段与重复问题直接可见。</p></div><div class="review-controls"><label><input id="filterExactFiles" type="checkbox" ${supplierFilters.exact?'checked':''}> 仅查看相同文件</label><label><input id="filterAttributeFiles" type="checkbox" ${supplierFilters.attribute?'checked':''}> 仅查看属性重复文件</label><span class="compact-actions"><button data-expand-suppliers class="icon-button" title="全部展开" aria-label="全部展开">+</button><button data-collapse-suppliers class="icon-button" title="全部收起" aria-label="全部收起">−</button></span></div></div><div class="supplier-board" style="--supplier-count:${Math.max(1,data.supplierStats.length)}">${data.supplierStats.map(stat=>supplierColumn(stat,sets,data)).join('')}</div>`;bindFileButtons(root);$('#filterExactFiles').onchange=event=>{supplierFilters.exact=event.target.checked;renderOverview();};$('#filterAttributeFiles').onchange=event=>{supplierFilters.attribute=event.target.checked;renderOverview();};root.querySelector('[data-expand-suppliers]').onclick=()=>setSupplierFilesOpen(root,true);root.querySelector('[data-collapse-suppliers]').onclick=()=>setSupplierFilesOpen(root,false);}
function refsForGroup(group){return group.files.map(ref=>{const file=allFiles().find(item=>item.submissionId===String(ref.key||'').split('|')[0]&&item.zipPath===ref.path)||allFiles().find(item=>item.supplier===ref.supplier&&item.zipPath===ref.path);return file?fileButton(file,'match-file'):`<div class="match-file"><span class="supplier-tag">${esc(ref.supplier)}</span><span>${esc(ref.path)}</span><small>${fmt(ref.size)}</small></div>`;}).join('');}
function duplicateFileRow(group,ref){const file=allFiles().find(item=>item.supplier===ref.supplier&&item.zipPath===ref.path),key=file?.key||ref.key,detail=`${group.label}：${group.value}`;return `<button class="duplicate-file-row" data-file-key="${esc(key)}"><span class="duplicate-file-name"><span class="supplier-tag">${esc(ref.supplier)}</span>${pathMarkup(ref.path)}</span><span class="duplicate-evidence"><strong>${esc(detail)}</strong><small>${esc(group.riskLevel||'低风险')}</small></span></button>`;}
function renderAttributeReview(){const data=audit(),root=$('#compareAttributes'),cards=groups=>groups.map(group=>`<article class="match-card duplicate-card"><div class="match-head"><strong>${group.kind==='simhash'?'文本':group.kind==='media'?'媒体':typeName(group.kind)} · ${esc(group.label)}：${esc(group.value)}</strong><span class="risk-chip risk-${group.riskLevel==='高风险'?'high':group.riskLevel==='中风险'?'medium':'low'}">${esc(group.riskLevel||'低风险')} · ${group.suppliers.length} 家供应商</span></div><div class="duplicate-files">${group.files.map(ref=>duplicateFileRow(group,ref)).join('')}</div></article>`).join('');root.innerHTML=`<div class="notice">所有非空重复属性都会列出；完全相同文件、SimHash 与媒体指纹由系统自动审查，无需手动选择。</div><div class="section-heading"><div><h2>跨供应商属性重复</h2><p>按“字段 + 标准化值”分组；完整路径与重复数据并排展示。</p></div><span>${data.attributeMatches.length} 组</span></div><div class="match-list duplicate-list">${data.attributeMatches.length?cards(data.attributeMatches):'<div class="empty-state"><div><strong>没有发现跨供应商属性重复</strong></div></div>'}</div><div class="section-heading"><div><h2>文本与媒体相似性线索</h2><p>展示文本 SimHash 与 Office 内嵌图片、媒体指纹证据。</p></div><span>${data.similarityMatches.length} 组</span></div><div class="match-list duplicate-list">${data.similarityMatches.length?cards(data.similarityMatches):'<div class="empty-state"><div><strong>没有发现文本或媒体相似性线索</strong></div></div>'}</div>`;bindFileButtons(root);}
function renderOperationReport(){const root=$('#compareReport'),logs=project.operationLog||[];root.innerHTML=`<div class="section-heading"><div><h2>操作记录</h2><p>记录属性修改、删除、保存和另存为结果，可随项目与报告导出。</p></div><span>${logs.length} 条</span></div>${logs.length?`<table class="report-table"><thead><tr><th>时间</th><th>供应商</th><th>文件</th><th>操作</th><th>修改内容</th><th>结果</th></tr></thead><tbody>${logs.map(log=>`<tr><td>${esc(new Date(log.at||log.createdAt).toLocaleString())}</td><td>${esc(log.supplier||'本地文件')}</td><td>${esc(log.file||log.zipPath)}</td><td>${esc(log.action==='save'?'保存':'另存为')}</td><td>${esc([...(log.changedFields||[]),...(log.deletedFields||[]).map(field=>`删除 ${field}`)].join('、')||'—')}</td><td>${esc(log.destination||'')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state"><div><strong>尚无文件操作</strong><p>在右侧属性编辑器保存修改后，操作会记录在这里。</p></div></div>'}`;}
function renderActiveSection(){for(const name of ['overview','attributes','report'])$('#compare'+name[0].toUpperCase()+name.slice(1)).hidden=name!==activeSection;$$('.workspace-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.section===activeSection));if(activeSection==='overview')renderOverview();if(activeSection==='attributes')renderAttributeReview();if(activeSection==='report')renderOperationReport();}
function renderCompare(){const data=audit();$('#compareProjectName').textContent=project.name;$('#compareSummary').textContent=`${data.summary.supplierCount} 家供应商 · ${data.summary.fileCount} 个文件 · ${data.summary.exactFileGroups} 组相同文件 · ${data.summary.attributeMatchGroups} 组属性重复 · ${data.summary.similarityMatchGroups||0} 组相似性线索`;renderActiveSection();}
$$('.workspace-tab').forEach(tab=>tab.onclick=()=>{activeSection=tab.dataset.section;renderActiveSection();});
function openCompareFile(key){const file=findFile(key);if(!file)return;selectedFileKey=key;$('#propertyDrawer').hidden=false;$('#drawerContext').textContent=`${file.supplier} / ${file.name}`;renderFileDetail(file,$('#drawerDetail'));}
$('#closeDrawer').onclick=()=>$('#propertyDrawer').hidden=true;

function renderEditor(){const files=allFiles(),query=($('#fileSearch').value||'').toLowerCase(),filtered=files.filter(file=>(file.name+' '+file.zipPath).toLowerCase().includes(query));$('#editorSummary').textContent=`${files.length} 个本地文件 · 直接查看、修改或清理支持的文档属性`;$('#editorFileCount').textContent=`${filtered.length}`;$('#editorFileList').innerHTML=filtered.map(file=>`<button class="file-row ${selectedFileKey===file.key?'selected':''}" data-editor-file="${esc(file.key)}"><span class="file-kind">${typeName(file.kind)}</span><span><strong>${esc(file.name)}</strong><small class="file-row-path">${esc(file.sourcePath||file.zipPath)}</small><small>${fmt(file.size)}</small></span></button>`).join('');$$('[data-editor-file]').forEach(button=>button.onclick=()=>{selectedFileKey=button.dataset.editorFile;renderEditor();const file=findFile(selectedFileKey);$('#editorDetail').className='editor-detail';renderFileDetail(file,$('#editorDetail'));});if(selectedFileKey){const file=findFile(selectedFileKey);if(file&&!$('#editorDetail .file-detail-sticky'))renderFileDetail(file,$('#editorDetail'));}}
async function addEditorFiles(){const selected=await window.api.pickFiles();if(!selected.length)return;inputFiles=[...new Set([...inputFiles,...selected])];showView('working');project=await window.api.analyze(inputFiles,{mode:'files'});selectedFileKey='';renderEditor();showView('editorWorkspace');}
$('#fileSearch').oninput=renderEditor;$('#addEditorFiles').onclick=addEditorFiles;$('#addEditorFilesInline').onclick=addEditorFiles;
function setExplorerWidth(value){const layout=$('.editor-layout'),max=Math.max(280,layout.getBoundingClientRect().width*.55);layout.style.setProperty('--explorer-width',`${Math.min(max,Math.max(220,value))}px`);}
$('#editorSplitter').onpointerdown=event=>{const splitter=event.currentTarget,startX=event.clientX,startWidth=$('.explorer').getBoundingClientRect().width;splitter.setPointerCapture(event.pointerId);splitter.classList.add('dragging');splitter.onpointermove=move=>setExplorerWidth(startWidth+move.clientX-startX);splitter.onpointerup=()=>{splitter.classList.remove('dragging');splitter.onpointermove=null;splitter.onpointerup=null;};};
$('#editorSplitter').onkeydown=event=>{if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();setExplorerWidth($('.explorer').getBoundingClientRect().width+(event.key==='ArrowRight'?20:-20));};

function displayValue(value){if(Array.isArray(value))return value.map(item=>typeof item==='object'?esc(JSON.stringify(item)):esc(item)).join('<br>');if(value&&typeof value==='object')return `<pre>${esc(JSON.stringify(value,null,2))}</pre>`;if(typeof value==='boolean')return value?'是':'否';return esc(value);}
function renderFileDetail(file,root){
  if(!file)return;const q=selector=>root.querySelector(selector),qa=selector=>[...root.querySelectorAll(selector)],groups=file.propertyGroups||[],canEdit=['word','excel','powerpoint','pdf'].includes(file.kind),office=file.kind!=='pdf',stateKey=`${file.sourcePath||file.containerPath||file.supplier}|${file.zipPath}`,unlinked=metadataLinkState.get(stateKey)||new Set();
  const labels={作者:'author','最后一次保存者':'lastEditor',修订号:'revision',版本号:'appVersion',程序名称:'application',公司:'company',管理者:'manager','创建内容的时间':'created','最后一次保存的日期':'modified',标题:'title',主题:'subject',关键词:'keywords',说明:'description',模板:'template','创建程序':'creator','制作工具':'producer','创建时间':'created','修改时间':'modified','自定义属性哈希':'customProperties'};
  const pdfFields=new Set(['author','title','subject','keywords','created','modified','creator','producer']),officeFields=new Set(['author','lastEditor','revision','appVersion','application','company','manager','created','modified','lastPrinted','title','subject','keywords','description','template','customProperties']),supported=field=>canEdit&&(office?officeFields:pdfFields).has(field),editable=field=>field!=='customProperties';
  const normalRow=(name,value)=>{const field=labels[name];if(!field||!supported(field))return `<dt>${esc(name)}</dt><dd>${displayValue(value)}</dd>`;const current=file.attributes?.[field]??(field==='appVersion'?file.attributes?.version:''),shown=current==null||current==='未提取到'?'':current;return `<dt>${esc(name)}</dt><dd class="property-editor"><label class="delete-property" title="选择此属性"><input type="checkbox" data-field="${field}" data-source="info"></label>${editable(field)?`<input class="property-value" data-field="${field}" data-source="info" data-original="${esc(shown)}" value="${esc(shown)}" aria-label="修改${esc(name)}">`:`<span>${displayValue(value)}</span>`}</dd>`;};
  const metadataCell=(name,item,source)=>{if(source==='info'&&item.infoReadOnly)return '<div class="metadata-cell metadata-na">不适用</div>';const shown=item[source]==='未提取到'?'':item[source],readonly=source==='xmp'&&!unlinked.has(item.field)?'readonly':'';return `<div class="metadata-cell"><label class="delete-property" title="选择此属性"><input type="checkbox" data-field="${item.field}" data-source="${source}"></label><input class="property-value" data-field="${item.field}" data-source="${source}" data-original="${esc(shown)}" value="${esc(shown)}" ${readonly} aria-label="修改 ${esc(name)} ${source==='info'?'Info':'XMP'} 值"></div>`;};
  const metadataRow=(name,item)=>{const linked=!unlinked.has(item.field);return `<div class="metadata-row"><div class="metadata-name">${esc(name)}</div>${metadataCell(name,item,'info')}<button class="field-link ${linked?'linked':'unlinked'}" data-field="${item.field}" title="${linked?'点击解除 Info 与 XMP 联动':'已解除，点击恢复联动'}">${linked?'🔗':'⛓'}</button>${metadataCell(name,item,'xmp')}</div>`;};
  const toolbar=canEdit?`<section class="edit-toolbar"><div class="bulk-actions"><label class="toolbar-check"><input type="checkbox" data-select-all> 全选</label></div><div class="save-summary"><span data-split-warning hidden>部分 Info 与 XMP 已解除关联，不同阅读器可能显示不同值。</span><span data-save-status role="status">${file.sourcePath?'保存会覆盖当前文件。':'ZIP 内文件只能另存为。'}</span></div><div class="edit-buttons"><small data-selected-count>已选择 0 项</small><label class="toolbar-check delete-mark"><input type="checkbox" data-mark-delete disabled> 删除所选属性</label><button data-save ${file.sourcePath?'':'disabled'}>保存</button><button data-save-as class="primary">另存为</button></div></section>`:'';
  const groupHtml=group=>group.id==='pdf-metadata'?`<details class="property-section" open><summary><span>${esc(group.title)}</span><small>${Object.keys(group.items).length} 项 · XMP ${esc(group.xmpStatus)}</small></summary><div class="metadata-table"><div class="metadata-row metadata-head"><div>属性</div><div>传统 PDF Info Dictionary</div><div></div><div>XMP Metadata Stream</div></div>${Object.entries(group.items).map(([name,item])=>metadataRow(name,item)).join('')}</div></details>`:`<details class="property-section" open><summary><span>${esc(group.title)}</span><small>${Object.keys(group.items).length} 项</small></summary><dl>${Object.entries(group.items).map(([name,value])=>normalRow(name,value)).join('')}</dl></details>`;
  root.innerHTML=`<div class="file-detail-sticky"><div class="file-title-line"><div class="file-name-row" title="${esc(file.name)}">${esc(file.name)}</div><div class="detail-section-actions"><button class="icon-button" data-expand-sections title="全部展开" aria-label="全部展开">+</button><button class="icon-button" data-collapse-sections title="全部收起" aria-label="全部收起">−</button></div></div><div class="file-info-row"><span>${esc(file.supplier)}</span><span>${typeName(file.kind)}</span><span class="path-muted" title="${esc(file.zipPath)}">${esc(file.zipPath)}</span><span data-file-size>${fmt(file.size)}</span></div>${toolbar}</div><div>${groups.map(groupHtml).join('')}</div>`;
  q('[data-expand-sections]').onclick=()=>qa('.property-section').forEach(section=>section.open=true);q('[data-collapse-sections]').onclick=()=>qa('.property-section').forEach(section=>section.open=false);
  if(!canEdit)return;
  let lastEditable=null;const twin=(selector,node)=>q(`${selector}[data-field="${node.dataset.field}"][data-source="${node.dataset.source==='xmp'?'info':'xmp'}"]`),isLinked=field=>!!q(`.field-link[data-field="${field}"].linked`),updateInput=input=>{const box=q(`.delete-property input[data-field="${input.dataset.field}"][data-source="${input.dataset.source}"]`);input.disabled=false;input.readOnly=(input.dataset.source==='xmp'&&isLinked(input.dataset.field))||box?.dataset.armed==='true';},showStatus=(message,state='')=>{const status=q('[data-save-status]');status.textContent=message;status.dataset.state=state;};
  const updateSelection=()=>{const boxes=qa('.delete-property input'),selected=boxes.filter(box=>box.checked),count=new Set(selected.map(box=>box.dataset.field)).size,all=q('[data-select-all]'),mark=q('[data-mark-delete]');q('[data-selected-count]').textContent=`已选择 ${count} 项`;all.checked=boxes.length>0&&selected.length===boxes.length;all.indeterminate=selected.length>0&&selected.length<boxes.length;mark.disabled=count===0;if(!count){mark.checked=false;boxes.forEach(box=>delete box.dataset.armed);}};
  qa('.delete-property input').forEach(box=>box.onchange=()=>{if(isLinked(box.dataset.field)){const other=twin('.delete-property input',box);if(other)other.checked=box.checked;}qa('.delete-property input').forEach(item=>delete item.dataset.armed);q('[data-mark-delete]').checked=false;updateSelection();qa('.property-value').forEach(updateInput);});
  qa('.property-value').forEach(input=>{input.onfocus=()=>{if(!input.readOnly)lastEditable=input;};input.oninput=()=>{if(isLinked(input.dataset.field)){const other=twin('.property-value',input);if(other)other.value=input.value;}};});
  qa('.field-link').forEach(button=>button.onclick=()=>{button.classList.toggle('linked');button.classList.toggle('unlinked');button.textContent=button.classList.contains('linked')?'🔗':'⛓';if(button.classList.contains('linked'))unlinked.delete(button.dataset.field);else unlinked.add(button.dataset.field);metadataLinkState.set(stateKey,unlinked);const xmp=q(`.property-value[data-field="${button.dataset.field}"][data-source="xmp"]`),info=q(`.property-value[data-field="${button.dataset.field}"][data-source="info"]`);if(button.classList.contains('linked')&&info&&xmp)xmp.value=info.value;if(xmp)updateInput(xmp);q('[data-split-warning]').hidden=!qa('.field-link.unlinked').length;});
  q('[data-select-all]').onchange=event=>{qa('.delete-property input').forEach(box=>{box.checked=event.target.checked;delete box.dataset.armed;});q('[data-mark-delete]').checked=false;qa('.property-value').forEach(updateInput);updateSelection();};
  q('[data-mark-delete]').onchange=event=>{qa('.delete-property input:checked').forEach(box=>{if(event.target.checked)box.dataset.armed='true';else delete box.dataset.armed;});qa('.property-value').forEach(updateInput);q('[data-selected-count]').textContent=`已选择 ${new Set(qa('.delete-property input:checked').map(box=>box.dataset.field)).size} 项${event.target.checked?'，保存时删除':''}`;};
  const submit=async action=>{const syncMetadata=file.kind!=='pdf'||qa('.field-link').every(link=>link.classList.contains('linked')),fields=qa('.delete-property input:checked').filter(box=>box.dataset.armed==='true'&&box.dataset.source!=='xmp').map(box=>box.dataset.field),xmpFields=qa('.delete-property input:checked').filter(box=>box.dataset.armed==='true'&&box.dataset.source==='xmp').map(box=>box.dataset.field),updates={},xmpUpdates={};qa('.property-value').forEach(input=>{const deleted=(input.dataset.source==='xmp'?xmpFields:fields).includes(input.dataset.field);if(!deleted&&input.value!==String(input.dataset.original??''))(input.dataset.source==='xmp'?xmpUpdates:updates)[input.dataset.field]=input.value;});if(!fields.length&&!xmpFields.length&&!Object.keys(updates).length&&!Object.keys(xmpUpdates).length){showStatus(qa('.delete-property input:checked').length?'请先勾选“删除所选属性”，再保存。':'没有需要保存的属性更改','warning');return;}const save=q('[data-save]'),saveAs=q('[data-save-as]');save.disabled=true;saveAs.disabled=true;showStatus(action==='save'?'正在写入并验证属性…':'正在生成并验证副本…','working');try{const result=await window.api.clean({sourcePath:file.sourcePath,zipPath:file.containerPath,entryPath:file.zipPath,kind:file.kind,fields,updates,xmpFields,xmpUpdates,syncMetadata,action,supplier:file.supplier,submissionId:file.submissionId});if(!result){showStatus('操作已取消');return;}if(action==='save'){updateProjectFile(file,result.verifiedFile);qa('.property-value').forEach(input=>{const attrs=result.verifiedFile.attributes||{},next=input.dataset.source==='xmp'?(attrs.xmp?.[input.dataset.field]??''):(attrs[input.dataset.field]??(input.dataset.field==='appVersion'?attrs.version:'')??'');input.value=String(next==='未提取到'?'':next);input.dataset.original=input.value;});qa('.delete-property input').forEach(box=>{box.checked=false;delete box.dataset.armed;});qa('.property-value').forEach(updateInput);updateSelection();q('[data-file-size]').textContent=fmt(file.size);showStatus('已保存并验证，可以继续编辑。','success');const resume=lastEditable?.isConnected&&!lastEditable.readOnly?lastEditable:qa('.property-value').find(input=>!input.readOnly);if(resume)requestAnimationFrame(()=>{resume.focus({preventScroll:true});resume.setSelectionRange(resume.value.length,resume.value.length);});}else showStatus(`已另存为并验证：${result.destination}`,'success');const operation=result.operation||{at:new Date().toISOString(),supplier:file.supplier,file:file.zipPath,action,destination:result.destination,changedFields:[...Object.keys(updates),...Object.keys(xmpUpdates).map(field=>`XMP ${field}`)],deletedFields:[...fields,...xmpFields.map(field=>`XMP ${field}`)]};project.operationLog=project.operationLog||[];if(!project.operationLog.some(item=>item.id&&item.id===operation.id))project.operationLog.push(operation);if(activeSection==='report')renderOperationReport();}catch(error){showStatus('保存失败：'+error.message,'error');}finally{save.disabled=!file.sourcePath;saveAs.disabled=false;}};
  q('[data-save]').onclick=()=>submit('save');q('[data-save-as]').onclick=()=>submit('saveAs');qa('.property-value').forEach(updateInput);q('[data-split-warning]').hidden=!qa('.field-link.unlinked').length;updateSelection();
}

$$('.backHome').forEach(button=>button.onclick=()=>showView('start'));$('#newWorkspace').onclick=()=>{project=null;inputFiles=[];selectedFileKey='';metadataLinkState.clear();showView('start');renderChosen();};
$('#saveProject').onclick=$('#saveEditorProject').onclick=()=>window.api.save();$('#exportPdf').onclick=()=>window.api.export('pdf');$('#exportXlsx').onclick=()=>window.api.export('xlsx');
$('#openProject').onclick=async()=>{const opened=await window.api.open();if(!opened)return;project=opened;project.operationLog=project.operationLog||[];metadataLinkState.clear();selectedFileKey='';mode=project.mode==='files'?'files':'compare';setMode(mode,{clear:false});if(mode==='files'){renderEditor();showView('editorWorkspace');}else{activeSection='overview';renderCompare();showView('compareWorkspace');}};
setMode('compare');showView('start');
