'use strict';
const fs=require('fs').promises;
const path=require('path');
const yauzl=require('yauzl');
const yazl=require('yazl');

const mediaRoots={word:/^word\/media\//i,excel:/^xl\/media\//i,powerpoint:/^ppt\/media\//i};
const mimeByExt={png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',bmp:'image/bmp',webp:'image/webp',svg:'image/svg+xml',tif:'image/tiff',tiff:'image/tiff',emf:'image/x-emf',wmf:'image/x-wmf',mp4:'video/mp4',m4v:'video/mp4',webm:'video/webm',ogv:'video/ogg',ogg:'video/ogg',mov:'video/quicktime',avi:'video/x-msvideo',wmv:'video/x-ms-wmv',mpg:'video/mpeg',mpeg:'video/mpeg'};
const imagePreviewable=new Set(['png','jpg','jpeg','gif','bmp','webp','svg']),videoPreviewable=new Set(['mp4','m4v','webm','ogv','ogg','mov']);
function kindFor(file){const extension=path.extname(file).toLowerCase();if(['.docx','.docm'].includes(extension))return'word';if(['.xlsx','.xlsm'].includes(extension))return'excel';if(['.pptx','.pptm'].includes(extension))return'powerpoint';return'';}
function readEntry(zip,entry){return new Promise((resolve,reject)=>zip.openReadStream(entry,(error,stream)=>{if(error)return reject(error);const chunks=[];let size=0;stream.on('data',chunk=>{size+=chunk.length;if(size>64*1024*1024){stream.destroy(new Error('单张图片超过 64 MB 限制'));return;}chunks.push(chunk);});stream.on('end',()=>resolve(Buffer.concat(chunks)));stream.on('error',reject);}));}
function dimensions(buffer,ext){try{if(ext==='png'&&buffer.length>=24)return{width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};if(ext==='gif'&&buffer.length>=10)return{width:buffer.readUInt16LE(6),height:buffer.readUInt16LE(8)};if(ext==='bmp'&&buffer.length>=26)return{width:buffer.readInt32LE(18),height:Math.abs(buffer.readInt32LE(22))};if(['jpg','jpeg'].includes(ext)){let offset=2;while(offset+9<buffer.length){if(buffer[offset]!==0xff){offset++;continue;}const marker=buffer[offset+1],length=buffer.readUInt16BE(offset+2);if(marker>=0xc0&&marker<=0xc3)return{height:buffer.readUInt16BE(offset+5),width:buffer.readUInt16BE(offset+7)};offset+=2+length;}}}catch{}return{};}
async function inspectFile(sourcePath,onEntry=()=>{}){const kind=kindFor(sourcePath);if(!kind)return{sourcePath,name:path.basename(sourcePath),kind:'other',images:[],error:'仅支持 Word、Excel 和 PowerPoint'};const input=await fs.readFile(sourcePath);return new Promise((resolve,reject)=>yauzl.fromBuffer(input,{lazyEntries:true,autoClose:false,decodeStrings:true,validateEntrySizes:true},(error,zip)=>{if(error)return reject(error);const images=[];let scanned=0;const total=zip.entryCount||1;zip.on('entry',async entry=>{try{scanned++;onEntry({scanned,total,media:images.length,entry:entry.fileName});if(!mediaRoots[kind].test(entry.fileName)||/\/$/.test(entry.fileName)){zip.readEntry();return;}const ext=path.extname(entry.fileName).slice(1).toLowerCase();if(!mimeByExt[ext]){zip.readEntry();return;}const data=await readEntry(zip,entry),mediaType=mimeByExt[ext].startsWith('video/')?'video':'image',size=mediaType==='image'?dimensions(data,ext):{};images.push({id:`${sourcePath}::${entry.fileName}`,entryPath:entry.fileName,name:path.basename(entry.fileName),ext,mime:mimeByExt[ext],mediaType,bytes:data.length,previewable:mediaType==='video'?videoPreviewable.has(ext):imagePreviewable.has(ext),processable:mediaType==='image'&&imagePreviewable.has(ext),data:data.toString('base64'),...size});onEntry({scanned,total,media:images.length,entry:entry.fileName});setImmediate(()=>zip.readEntry());}catch(failure){zip.close();reject(failure);}});zip.on('end',()=>{zip.close();resolve({sourcePath,name:path.basename(sourcePath),kind,bytes:input.length,images});});zip.on('error',reject);zip.readEntry();}));}
async function inspectOfficeImages(files,progress=()=>{}){const results=[];for(let index=0;index<files.length;index++){const sourcePath=path.resolve(files[index]),fileName=path.basename(sourcePath);let lastScanned=0,lastMedia=-1;progress({done:index,total:files.length,name:fileName});try{results.push(await inspectFile(sourcePath,state=>{const mediaMilestone=state.media!==lastMedia&&state.media%8===0,entryMilestone=state.scanned-lastScanned>=12;if(state.scanned!==state.total&&!mediaMilestone&&!entryMilestone)return;lastScanned=state.scanned;lastMedia=state.media;progress({done:index+(state.scanned/state.total),total:files.length,name:`${fileName} · 已发现 ${state.media} 项媒体`});}));}catch(error){results.push({sourcePath,name:fileName,kind:kindFor(sourcePath)||'other',images:[],error:error.message});}}progress({done:files.length,total:files.length,name:'媒体提取完成'});return results;}
async function replaceOfficeMedia(sourcePath,replacements,destination=sourcePath){
  if(!kindFor(sourcePath))throw new Error('仅支持 Word、Excel 和 PowerPoint 源文件');
  const replacementMap=new Map(replacements.map(item=>[item.entryPath,Buffer.isBuffer(item.data)?item.data:Buffer.from(item.data,'base64')]));
  if(!replacementMap.size)throw new Error('没有可写回源文件的媒体修改');
  const input=await fs.readFile(sourcePath),archive=await new Promise((resolve,reject)=>yauzl.fromBuffer(input,{lazyEntries:true,autoClose:false,decodeStrings:true},(error,zip)=>error?reject(error):resolve(zip))),output=new yazl.ZipFile(),chunks=[];
  output.outputStream.on('data',chunk=>chunks.push(chunk));
  const finished=new Promise((resolve,reject)=>{output.outputStream.on('end',()=>resolve(Buffer.concat(chunks)));output.outputStream.on('error',reject);});
  await new Promise((resolve,reject)=>{archive.on('entry',async entry=>{try{if(/\/$/.test(entry.fileName)){output.addEmptyDirectory(entry.fileName);archive.readEntry();return;}const data=replacementMap.has(entry.fileName)?replacementMap.get(entry.fileName):await readEntry(archive,entry);output.addBuffer(data,entry.fileName,{mtime:entry.getLastModDate()});archive.readEntry();}catch(error){reject(error);}});archive.on('end',()=>{archive.close();resolve();});archive.on('error',reject);archive.readEntry();});
  output.end();const buffer=await finished,target=path.resolve(destination),source=path.resolve(sourcePath),temporary=target===source?path.join(path.dirname(source),`.${path.basename(source)}.presalesx-${process.pid}-${Date.now()}.tmp`):target;
  await fs.writeFile(temporary,buffer);if(target===source){await fs.copyFile(temporary,source);await fs.unlink(temporary);}
  return{sourcePath:source,destination:target,replaced:replacementMap.size,bytes:buffer.length};
}
module.exports={inspectOfficeImages,replaceOfficeMedia,kindFor,dimensions};
